#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPR_OCEL_Enhance.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_ONLINE_EXAM_OCEL")]
	public partial class cpmd_dataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_M_READING_TASK(TBL_M_READING_TASK instance);
    partial void UpdateTBL_M_READING_TASK(TBL_M_READING_TASK instance);
    partial void DeleteTBL_M_READING_TASK(TBL_M_READING_TASK instance);
    partial void InsertTBL_R_HANDBOOK_CPMD(TBL_R_HANDBOOK_CPMD instance);
    partial void UpdateTBL_R_HANDBOOK_CPMD(TBL_R_HANDBOOK_CPMD instance);
    partial void DeleteTBL_R_HANDBOOK_CPMD(TBL_R_HANDBOOK_CPMD instance);
    partial void InsertTBL_T_READING_REGISTRATION(TBL_T_READING_REGISTRATION instance);
    partial void UpdateTBL_T_READING_REGISTRATION(TBL_T_READING_REGISTRATION instance);
    partial void DeleteTBL_T_READING_REGISTRATION(TBL_T_READING_REGISTRATION instance);
    partial void InsertTBL_T_USER_ANSWER(TBL_T_USER_ANSWER instance);
    partial void UpdateTBL_T_USER_ANSWER(TBL_T_USER_ANSWER instance);
    partial void DeleteTBL_T_USER_ANSWER(TBL_T_USER_ANSWER instance);
    partial void InsertTBL_R_COMPETENCY(TBL_R_COMPETENCY instance);
    partial void UpdateTBL_R_COMPETENCY(TBL_R_COMPETENCY instance);
    partial void DeleteTBL_R_COMPETENCY(TBL_R_COMPETENCY instance);
    partial void InsertTBL_R_MODULE_CLASS(TBL_R_MODULE_CLASS instance);
    partial void UpdateTBL_R_MODULE_CLASS(TBL_R_MODULE_CLASS instance);
    partial void DeleteTBL_R_MODULE_CLASS(TBL_R_MODULE_CLASS instance);
    partial void InsertTBL_MODULE_SET(TBL_MODULE_SET instance);
    partial void UpdateTBL_MODULE_SET(TBL_MODULE_SET instance);
    partial void DeleteTBL_MODULE_SET(TBL_MODULE_SET instance);
    #endregion
		
		public cpmd_dataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_ONLINE_EXAM_OCELConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public cpmd_dataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public cpmd_dataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public cpmd_dataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public cpmd_dataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_M_READING_TASK> TBL_M_READING_TASKs
		{
			get
			{
				return this.GetTable<TBL_M_READING_TASK>();
			}
		}
		
		public System.Data.Linq.Table<TBL_R_HANDBOOK_CPMD> TBL_R_HANDBOOK_CPMDs
		{
			get
			{
				return this.GetTable<TBL_R_HANDBOOK_CPMD>();
			}
		}
		
		public System.Data.Linq.Table<TBL_T_READING_REGISTRATION> TBL_T_READING_REGISTRATIONs
		{
			get
			{
				return this.GetTable<TBL_T_READING_REGISTRATION>();
			}
		}
		
		public System.Data.Linq.Table<VW_TASKLIST_DETAIL> VW_TASKLIST_DETAILs
		{
			get
			{
				return this.GetTable<VW_TASKLIST_DETAIL>();
			}
		}
		
		public System.Data.Linq.Table<TBL_T_USER_ANSWER> TBL_T_USER_ANSWERs
		{
			get
			{
				return this.GetTable<TBL_T_USER_ANSWER>();
			}
		}
		
		public System.Data.Linq.Table<TBL_R_COMPETENCY> TBL_R_COMPETENCies
		{
			get
			{
				return this.GetTable<TBL_R_COMPETENCY>();
			}
		}
		
		public System.Data.Linq.Table<VW_R_MODULE> VW_R_MODULEs
		{
			get
			{
				return this.GetTable<VW_R_MODULE>();
			}
		}
		
		public System.Data.Linq.Table<TBL_R_MODULE_CLASS> TBL_R_MODULE_CLASSes
		{
			get
			{
				return this.GetTable<TBL_R_MODULE_CLASS>();
			}
		}
		
		public System.Data.Linq.Table<VW_R_SUB_MODULE> VW_R_SUB_MODULEs
		{
			get
			{
				return this.GetTable<VW_R_SUB_MODULE>();
			}
		}
		
		public System.Data.Linq.Table<VW_T_READING_REPORT> VW_T_READING_REPORTs
		{
			get
			{
				return this.GetTable<VW_T_READING_REPORT>();
			}
		}
		
		public System.Data.Linq.Table<TBL_MODULE_SET> TBL_MODULE_SETs
		{
			get
			{
				return this.GetTable<TBL_MODULE_SET>();
			}
		}
		
		public System.Data.Linq.Table<VW_T_MODULE_SET> VW_T_MODULE_SETs
		{
			get
			{
				return this.GetTable<VW_T_MODULE_SET>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="cpmd.GetMyTaskList", IsComposable=true)]
		public IQueryable<GetMyTaskListResult> GetMyTaskList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NRP", DbType="VarChar(12)")] string nRP)
		{
			return this.CreateMethodCallQuery<GetMyTaskListResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nRP);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="cpmd.cufn_get_taskList_detail", IsComposable=true)]
		public IQueryable<cufn_get_taskList_detailResult> cufn_get_taskList_detail([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NRP", DbType="VarChar(12)")] string nRP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TASK_ID", DbType="VarChar(50)")] string tASK_ID)
		{
			return this.CreateMethodCallQuery<cufn_get_taskList_detailResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nRP, tASK_ID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="cpmd.cusp_updateReadingExamToReady")]
		public int cusp_updateReadingExamToReady([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string record_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string task_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(3)")] string competency_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string student_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> is_last_reading)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), record_id, task_id, competency_id, student_id, is_last_reading);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="cpmd.cusp_generate_soal_acak")]
		public ISingleResult<cusp_generate_soal_acakResult> cusp_generate_soal_acak([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TASK_ID", DbType="VarChar(40)")] string tASK_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NRP_EMP", DbType="VarChar(10)")] string nRP_EMP)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tASK_ID, nRP_EMP);
			return ((ISingleResult<cusp_generate_soal_acakResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="cpmd.cufn_get_list_detail", IsComposable=true)]
		public IQueryable<cufn_get_list_detailResult> cufn_get_list_detail([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string record_id)
		{
			return this.CreateMethodCallQuery<cufn_get_list_detailResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), record_id);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="ocel.cusp_Module")]
		public int cusp_Module([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(250)")] string v_MODULE_NAME, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string v_CMD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), v_MODULE_NAME, v_CMD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="ocel.cusp_Submodule")]
		public int cusp_Submodule([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(250)")] string v_MODULE_SUB_NAME, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(2)")] string v_MODULE_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string v_CMD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), v_MODULE_SUB_NAME, v_MODULE_ID, v_CMD);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="cpmd.TBL_M_READING_TASK")]
	public partial class TBL_M_READING_TASK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TASK_ID;
		
		private string _MODULE_ID;
		
		private string _NRP;
		
		private string _ASSIGN_DIV;
		
		private System.DateTime _ASSIGN_DATE;
		
		private int _IS_LOCK;
		
		private System.Nullable<System.DateTime> _UPDATE_DATE;
		
		private string _UPDATE_BY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTASK_IDChanging(string value);
    partial void OnTASK_IDChanged();
    partial void OnMODULE_IDChanging(string value);
    partial void OnMODULE_IDChanged();
    partial void OnNRPChanging(string value);
    partial void OnNRPChanged();
    partial void OnASSIGN_DIVChanging(string value);
    partial void OnASSIGN_DIVChanged();
    partial void OnASSIGN_DATEChanging(System.DateTime value);
    partial void OnASSIGN_DATEChanged();
    partial void OnIS_LOCKChanging(int value);
    partial void OnIS_LOCKChanged();
    partial void OnUPDATE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnUPDATE_DATEChanged();
    partial void OnUPDATE_BYChanging(string value);
    partial void OnUPDATE_BYChanged();
    #endregion
		
		public TBL_M_READING_TASK()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TASK_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TASK_ID
		{
			get
			{
				return this._TASK_ID;
			}
			set
			{
				if ((this._TASK_ID != value))
				{
					this.OnTASK_IDChanging(value);
					this.SendPropertyChanging();
					this._TASK_ID = value;
					this.SendPropertyChanged("TASK_ID");
					this.OnTASK_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE_ID", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MODULE_ID
		{
			get
			{
				return this._MODULE_ID;
			}
			set
			{
				if ((this._MODULE_ID != value))
				{
					this.OnMODULE_IDChanging(value);
					this.SendPropertyChanging();
					this._MODULE_ID = value;
					this.SendPropertyChanged("MODULE_ID");
					this.OnMODULE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this.OnNRPChanging(value);
					this.SendPropertyChanging();
					this._NRP = value;
					this.SendPropertyChanged("NRP");
					this.OnNRPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASSIGN_DIV", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string ASSIGN_DIV
		{
			get
			{
				return this._ASSIGN_DIV;
			}
			set
			{
				if ((this._ASSIGN_DIV != value))
				{
					this.OnASSIGN_DIVChanging(value);
					this.SendPropertyChanging();
					this._ASSIGN_DIV = value;
					this.SendPropertyChanged("ASSIGN_DIV");
					this.OnASSIGN_DIVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASSIGN_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime ASSIGN_DATE
		{
			get
			{
				return this._ASSIGN_DATE;
			}
			set
			{
				if ((this._ASSIGN_DATE != value))
				{
					this.OnASSIGN_DATEChanging(value);
					this.SendPropertyChanging();
					this._ASSIGN_DATE = value;
					this.SendPropertyChanged("ASSIGN_DATE");
					this.OnASSIGN_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_LOCK", DbType="Int NOT NULL")]
		public int IS_LOCK
		{
			get
			{
				return this._IS_LOCK;
			}
			set
			{
				if ((this._IS_LOCK != value))
				{
					this.OnIS_LOCKChanging(value);
					this.SendPropertyChanging();
					this._IS_LOCK = value;
					this.SendPropertyChanged("IS_LOCK");
					this.OnIS_LOCKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATE_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATE_DATE
		{
			get
			{
				return this._UPDATE_DATE;
			}
			set
			{
				if ((this._UPDATE_DATE != value))
				{
					this.OnUPDATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._UPDATE_DATE = value;
					this.SendPropertyChanged("UPDATE_DATE");
					this.OnUPDATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATE_BY", DbType="VarChar(10)")]
		public string UPDATE_BY
		{
			get
			{
				return this._UPDATE_BY;
			}
			set
			{
				if ((this._UPDATE_BY != value))
				{
					this.OnUPDATE_BYChanging(value);
					this.SendPropertyChanging();
					this._UPDATE_BY = value;
					this.SendPropertyChanged("UPDATE_BY");
					this.OnUPDATE_BYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="cpmd.TBL_R_HANDBOOK_CPMD")]
	public partial class TBL_R_HANDBOOK_CPMD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _HANDBOOK_PID;
		
		private string _MODULE_ID;
		
		private string _COMPETENCY_ID;
		
		private string _FILE_PATH;
		
		private string _FILE_NAME;
		
		private bool _IsActive;
		
		private System.Nullable<System.DateTime> _CREATED_DATE;
		
		private string _CREATED_BY;
		
		private System.Nullable<System.DateTime> _MODIF_DATE;
		
		private string _MODIF_BY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHANDBOOK_PIDChanging(string value);
    partial void OnHANDBOOK_PIDChanged();
    partial void OnMODULE_IDChanging(string value);
    partial void OnMODULE_IDChanged();
    partial void OnCOMPETENCY_IDChanging(string value);
    partial void OnCOMPETENCY_IDChanged();
    partial void OnFILE_PATHChanging(string value);
    partial void OnFILE_PATHChanged();
    partial void OnFILE_NAMEChanging(string value);
    partial void OnFILE_NAMEChanged();
    partial void OnIsActiveChanging(bool value);
    partial void OnIsActiveChanged();
    partial void OnCREATED_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATED_DATEChanged();
    partial void OnCREATED_BYChanging(string value);
    partial void OnCREATED_BYChanged();
    partial void OnMODIF_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnMODIF_DATEChanged();
    partial void OnMODIF_BYChanging(string value);
    partial void OnMODIF_BYChanged();
    #endregion
		
		public TBL_R_HANDBOOK_CPMD()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HANDBOOK_PID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string HANDBOOK_PID
		{
			get
			{
				return this._HANDBOOK_PID;
			}
			set
			{
				if ((this._HANDBOOK_PID != value))
				{
					this.OnHANDBOOK_PIDChanging(value);
					this.SendPropertyChanging();
					this._HANDBOOK_PID = value;
					this.SendPropertyChanged("HANDBOOK_PID");
					this.OnHANDBOOK_PIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE_ID", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MODULE_ID
		{
			get
			{
				return this._MODULE_ID;
			}
			set
			{
				if ((this._MODULE_ID != value))
				{
					this.OnMODULE_IDChanging(value);
					this.SendPropertyChanging();
					this._MODULE_ID = value;
					this.SendPropertyChanged("MODULE_ID");
					this.OnMODULE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPETENCY_ID", DbType="Char(2)")]
		public string COMPETENCY_ID
		{
			get
			{
				return this._COMPETENCY_ID;
			}
			set
			{
				if ((this._COMPETENCY_ID != value))
				{
					this.OnCOMPETENCY_IDChanging(value);
					this.SendPropertyChanging();
					this._COMPETENCY_ID = value;
					this.SendPropertyChanged("COMPETENCY_ID");
					this.OnCOMPETENCY_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FILE_PATH", DbType="VarChar(200)")]
		public string FILE_PATH
		{
			get
			{
				return this._FILE_PATH;
			}
			set
			{
				if ((this._FILE_PATH != value))
				{
					this.OnFILE_PATHChanging(value);
					this.SendPropertyChanging();
					this._FILE_PATH = value;
					this.SendPropertyChanged("FILE_PATH");
					this.OnFILE_PATHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FILE_NAME", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string FILE_NAME
		{
			get
			{
				return this._FILE_NAME;
			}
			set
			{
				if ((this._FILE_NAME != value))
				{
					this.OnFILE_NAMEChanging(value);
					this.SendPropertyChanging();
					this._FILE_NAME = value;
					this.SendPropertyChanged("FILE_NAME");
					this.OnFILE_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_DATE
		{
			get
			{
				return this._CREATED_DATE;
			}
			set
			{
				if ((this._CREATED_DATE != value))
				{
					this.OnCREATED_DATEChanging(value);
					this.SendPropertyChanging();
					this._CREATED_DATE = value;
					this.SendPropertyChanged("CREATED_DATE");
					this.OnCREATED_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_BY", DbType="VarChar(50)")]
		public string CREATED_BY
		{
			get
			{
				return this._CREATED_BY;
			}
			set
			{
				if ((this._CREATED_BY != value))
				{
					this.OnCREATED_BYChanging(value);
					this.SendPropertyChanging();
					this._CREATED_BY = value;
					this.SendPropertyChanged("CREATED_BY");
					this.OnCREATED_BYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIF_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MODIF_DATE
		{
			get
			{
				return this._MODIF_DATE;
			}
			set
			{
				if ((this._MODIF_DATE != value))
				{
					this.OnMODIF_DATEChanging(value);
					this.SendPropertyChanging();
					this._MODIF_DATE = value;
					this.SendPropertyChanged("MODIF_DATE");
					this.OnMODIF_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODIF_BY", DbType="VarChar(10)")]
		public string MODIF_BY
		{
			get
			{
				return this._MODIF_BY;
			}
			set
			{
				if ((this._MODIF_BY != value))
				{
					this.OnMODIF_BYChanging(value);
					this.SendPropertyChanging();
					this._MODIF_BY = value;
					this.SendPropertyChanged("MODIF_BY");
					this.OnMODIF_BYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="cpmd.TBL_T_READING_REGISTRATION")]
	public partial class TBL_T_READING_REGISTRATION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _RECORD_ID;
		
		private string _TASK_ID;
		
		private string _SUB_MODULE_ID;
		
		private string _STUDENT_ID;
		
		private string _DSTRCT_CODE;
		
		private string _DEPARTMENT;
		
		private string _PERIOD;
		
		private string _POSITION_CODE;
		
		private string _POSITION_DESC;
		
		private int _DURATION_MINUTE;
		
		private bool _IS_SELF_ASSESMENT;
		
		private System.DateTime _REGISTRATION_DATE;
		
		private string _EXAM_ACTUAL_DATE;
		
		private System.Nullable<System.DateTime> _EXAM_LOGIN_TIME;
		
		private System.Nullable<System.DateTime> _EXAM_FINISH_TIME;
		
		private byte _EXAM_STATUS;
		
		private double _EXAM_SCORE;
		
		private string _EVENT_ID;
		
		private System.Nullable<bool> _STATUS_READY_EXAM;
		
		private string _SUPPORT_LINK;
		
		private System.Nullable<double> _PERCENT_COMPLETE;
		
		private System.Nullable<double> _REMINDING_TIME;
		
		private System.Nullable<System.DateTime> _UPDATE_REMINDING_TIME;
		
		private string _EXAM_START_DATE;
		
		private int _IS_LOCKED;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRECORD_IDChanging(string value);
    partial void OnRECORD_IDChanged();
    partial void OnTASK_IDChanging(string value);
    partial void OnTASK_IDChanged();
    partial void OnSUB_MODULE_IDChanging(string value);
    partial void OnSUB_MODULE_IDChanged();
    partial void OnSTUDENT_IDChanging(string value);
    partial void OnSTUDENT_IDChanged();
    partial void OnDSTRCT_CODEChanging(string value);
    partial void OnDSTRCT_CODEChanged();
    partial void OnDEPARTMENTChanging(string value);
    partial void OnDEPARTMENTChanged();
    partial void OnPERIODChanging(string value);
    partial void OnPERIODChanged();
    partial void OnPOSITION_CODEChanging(string value);
    partial void OnPOSITION_CODEChanged();
    partial void OnPOSITION_DESCChanging(string value);
    partial void OnPOSITION_DESCChanged();
    partial void OnDURATION_MINUTEChanging(int value);
    partial void OnDURATION_MINUTEChanged();
    partial void OnIS_SELF_ASSESMENTChanging(bool value);
    partial void OnIS_SELF_ASSESMENTChanged();
    partial void OnREGISTRATION_DATEChanging(System.DateTime value);
    partial void OnREGISTRATION_DATEChanged();
    partial void OnEXAM_ACTUAL_DATEChanging(string value);
    partial void OnEXAM_ACTUAL_DATEChanged();
    partial void OnEXAM_LOGIN_TIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnEXAM_LOGIN_TIMEChanged();
    partial void OnEXAM_FINISH_TIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnEXAM_FINISH_TIMEChanged();
    partial void OnEXAM_STATUSChanging(byte value);
    partial void OnEXAM_STATUSChanged();
    partial void OnEXAM_SCOREChanging(double value);
    partial void OnEXAM_SCOREChanged();
    partial void OnEVENT_IDChanging(string value);
    partial void OnEVENT_IDChanged();
    partial void OnSTATUS_READY_EXAMChanging(System.Nullable<bool> value);
    partial void OnSTATUS_READY_EXAMChanged();
    partial void OnSUPPORT_LINKChanging(string value);
    partial void OnSUPPORT_LINKChanged();
    partial void OnPERCENT_COMPLETEChanging(System.Nullable<double> value);
    partial void OnPERCENT_COMPLETEChanged();
    partial void OnREMINDING_TIMEChanging(System.Nullable<double> value);
    partial void OnREMINDING_TIMEChanged();
    partial void OnUPDATE_REMINDING_TIMEChanging(System.Nullable<System.DateTime> value);
    partial void OnUPDATE_REMINDING_TIMEChanged();
    partial void OnEXAM_START_DATEChanging(string value);
    partial void OnEXAM_START_DATEChanged();
    partial void OnIS_LOCKEDChanging(int value);
    partial void OnIS_LOCKEDChanged();
    #endregion
		
		public TBL_T_READING_REGISTRATION()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECORD_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string RECORD_ID
		{
			get
			{
				return this._RECORD_ID;
			}
			set
			{
				if ((this._RECORD_ID != value))
				{
					this.OnRECORD_IDChanging(value);
					this.SendPropertyChanging();
					this._RECORD_ID = value;
					this.SendPropertyChanged("RECORD_ID");
					this.OnRECORD_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TASK_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TASK_ID
		{
			get
			{
				return this._TASK_ID;
			}
			set
			{
				if ((this._TASK_ID != value))
				{
					this.OnTASK_IDChanging(value);
					this.SendPropertyChanging();
					this._TASK_ID = value;
					this.SendPropertyChanged("TASK_ID");
					this.OnTASK_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_MODULE_ID", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string SUB_MODULE_ID
		{
			get
			{
				return this._SUB_MODULE_ID;
			}
			set
			{
				if ((this._SUB_MODULE_ID != value))
				{
					this.OnSUB_MODULE_IDChanging(value);
					this.SendPropertyChanging();
					this._SUB_MODULE_ID = value;
					this.SendPropertyChanged("SUB_MODULE_ID");
					this.OnSUB_MODULE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUDENT_ID", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string STUDENT_ID
		{
			get
			{
				return this._STUDENT_ID;
			}
			set
			{
				if ((this._STUDENT_ID != value))
				{
					this.OnSTUDENT_IDChanging(value);
					this.SendPropertyChanging();
					this._STUDENT_ID = value;
					this.SendPropertyChanged("STUDENT_ID");
					this.OnSTUDENT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this.OnDSTRCT_CODEChanging(value);
					this.SendPropertyChanging();
					this._DSTRCT_CODE = value;
					this.SendPropertyChanged("DSTRCT_CODE");
					this.OnDSTRCT_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPARTMENT", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string DEPARTMENT
		{
			get
			{
				return this._DEPARTMENT;
			}
			set
			{
				if ((this._DEPARTMENT != value))
				{
					this.OnDEPARTMENTChanging(value);
					this.SendPropertyChanging();
					this._DEPARTMENT = value;
					this.SendPropertyChanged("DEPARTMENT");
					this.OnDEPARTMENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERIOD", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string PERIOD
		{
			get
			{
				return this._PERIOD;
			}
			set
			{
				if ((this._PERIOD != value))
				{
					this.OnPERIODChanging(value);
					this.SendPropertyChanging();
					this._PERIOD = value;
					this.SendPropertyChanged("PERIOD");
					this.OnPERIODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_CODE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string POSITION_CODE
		{
			get
			{
				return this._POSITION_CODE;
			}
			set
			{
				if ((this._POSITION_CODE != value))
				{
					this.OnPOSITION_CODEChanging(value);
					this.SendPropertyChanging();
					this._POSITION_CODE = value;
					this.SendPropertyChanged("POSITION_CODE");
					this.OnPOSITION_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_DESC", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string POSITION_DESC
		{
			get
			{
				return this._POSITION_DESC;
			}
			set
			{
				if ((this._POSITION_DESC != value))
				{
					this.OnPOSITION_DESCChanging(value);
					this.SendPropertyChanging();
					this._POSITION_DESC = value;
					this.SendPropertyChanged("POSITION_DESC");
					this.OnPOSITION_DESCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DURATION_MINUTE", DbType="Int NOT NULL")]
		public int DURATION_MINUTE
		{
			get
			{
				return this._DURATION_MINUTE;
			}
			set
			{
				if ((this._DURATION_MINUTE != value))
				{
					this.OnDURATION_MINUTEChanging(value);
					this.SendPropertyChanging();
					this._DURATION_MINUTE = value;
					this.SendPropertyChanged("DURATION_MINUTE");
					this.OnDURATION_MINUTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_SELF_ASSESMENT", DbType="Bit NOT NULL")]
		public bool IS_SELF_ASSESMENT
		{
			get
			{
				return this._IS_SELF_ASSESMENT;
			}
			set
			{
				if ((this._IS_SELF_ASSESMENT != value))
				{
					this.OnIS_SELF_ASSESMENTChanging(value);
					this.SendPropertyChanging();
					this._IS_SELF_ASSESMENT = value;
					this.SendPropertyChanged("IS_SELF_ASSESMENT");
					this.OnIS_SELF_ASSESMENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REGISTRATION_DATE", DbType="Date NOT NULL")]
		public System.DateTime REGISTRATION_DATE
		{
			get
			{
				return this._REGISTRATION_DATE;
			}
			set
			{
				if ((this._REGISTRATION_DATE != value))
				{
					this.OnREGISTRATION_DATEChanging(value);
					this.SendPropertyChanging();
					this._REGISTRATION_DATE = value;
					this.SendPropertyChanged("REGISTRATION_DATE");
					this.OnREGISTRATION_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXAM_ACTUAL_DATE", DbType="VarChar(40)")]
		public string EXAM_ACTUAL_DATE
		{
			get
			{
				return this._EXAM_ACTUAL_DATE;
			}
			set
			{
				if ((this._EXAM_ACTUAL_DATE != value))
				{
					this.OnEXAM_ACTUAL_DATEChanging(value);
					this.SendPropertyChanging();
					this._EXAM_ACTUAL_DATE = value;
					this.SendPropertyChanged("EXAM_ACTUAL_DATE");
					this.OnEXAM_ACTUAL_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXAM_LOGIN_TIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> EXAM_LOGIN_TIME
		{
			get
			{
				return this._EXAM_LOGIN_TIME;
			}
			set
			{
				if ((this._EXAM_LOGIN_TIME != value))
				{
					this.OnEXAM_LOGIN_TIMEChanging(value);
					this.SendPropertyChanging();
					this._EXAM_LOGIN_TIME = value;
					this.SendPropertyChanged("EXAM_LOGIN_TIME");
					this.OnEXAM_LOGIN_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXAM_FINISH_TIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> EXAM_FINISH_TIME
		{
			get
			{
				return this._EXAM_FINISH_TIME;
			}
			set
			{
				if ((this._EXAM_FINISH_TIME != value))
				{
					this.OnEXAM_FINISH_TIMEChanging(value);
					this.SendPropertyChanging();
					this._EXAM_FINISH_TIME = value;
					this.SendPropertyChanged("EXAM_FINISH_TIME");
					this.OnEXAM_FINISH_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXAM_STATUS", DbType="TinyInt NOT NULL")]
		public byte EXAM_STATUS
		{
			get
			{
				return this._EXAM_STATUS;
			}
			set
			{
				if ((this._EXAM_STATUS != value))
				{
					this.OnEXAM_STATUSChanging(value);
					this.SendPropertyChanging();
					this._EXAM_STATUS = value;
					this.SendPropertyChanged("EXAM_STATUS");
					this.OnEXAM_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXAM_SCORE", DbType="Float NOT NULL")]
		public double EXAM_SCORE
		{
			get
			{
				return this._EXAM_SCORE;
			}
			set
			{
				if ((this._EXAM_SCORE != value))
				{
					this.OnEXAM_SCOREChanging(value);
					this.SendPropertyChanging();
					this._EXAM_SCORE = value;
					this.SendPropertyChanged("EXAM_SCORE");
					this.OnEXAM_SCOREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EVENT_ID", DbType="VarChar(100)")]
		public string EVENT_ID
		{
			get
			{
				return this._EVENT_ID;
			}
			set
			{
				if ((this._EVENT_ID != value))
				{
					this.OnEVENT_IDChanging(value);
					this.SendPropertyChanging();
					this._EVENT_ID = value;
					this.SendPropertyChanged("EVENT_ID");
					this.OnEVENT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_READY_EXAM", DbType="Bit")]
		public System.Nullable<bool> STATUS_READY_EXAM
		{
			get
			{
				return this._STATUS_READY_EXAM;
			}
			set
			{
				if ((this._STATUS_READY_EXAM != value))
				{
					this.OnSTATUS_READY_EXAMChanging(value);
					this.SendPropertyChanging();
					this._STATUS_READY_EXAM = value;
					this.SendPropertyChanged("STATUS_READY_EXAM");
					this.OnSTATUS_READY_EXAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUPPORT_LINK", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string SUPPORT_LINK
		{
			get
			{
				return this._SUPPORT_LINK;
			}
			set
			{
				if ((this._SUPPORT_LINK != value))
				{
					this.OnSUPPORT_LINKChanging(value);
					this.SendPropertyChanging();
					this._SUPPORT_LINK = value;
					this.SendPropertyChanged("SUPPORT_LINK");
					this.OnSUPPORT_LINKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERCENT_COMPLETE", DbType="Float")]
		public System.Nullable<double> PERCENT_COMPLETE
		{
			get
			{
				return this._PERCENT_COMPLETE;
			}
			set
			{
				if ((this._PERCENT_COMPLETE != value))
				{
					this.OnPERCENT_COMPLETEChanging(value);
					this.SendPropertyChanging();
					this._PERCENT_COMPLETE = value;
					this.SendPropertyChanged("PERCENT_COMPLETE");
					this.OnPERCENT_COMPLETEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REMINDING_TIME", DbType="Float")]
		public System.Nullable<double> REMINDING_TIME
		{
			get
			{
				return this._REMINDING_TIME;
			}
			set
			{
				if ((this._REMINDING_TIME != value))
				{
					this.OnREMINDING_TIMEChanging(value);
					this.SendPropertyChanging();
					this._REMINDING_TIME = value;
					this.SendPropertyChanged("REMINDING_TIME");
					this.OnREMINDING_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATE_REMINDING_TIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATE_REMINDING_TIME
		{
			get
			{
				return this._UPDATE_REMINDING_TIME;
			}
			set
			{
				if ((this._UPDATE_REMINDING_TIME != value))
				{
					this.OnUPDATE_REMINDING_TIMEChanging(value);
					this.SendPropertyChanging();
					this._UPDATE_REMINDING_TIME = value;
					this.SendPropertyChanged("UPDATE_REMINDING_TIME");
					this.OnUPDATE_REMINDING_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXAM_START_DATE", DbType="VarChar(40)")]
		public string EXAM_START_DATE
		{
			get
			{
				return this._EXAM_START_DATE;
			}
			set
			{
				if ((this._EXAM_START_DATE != value))
				{
					this.OnEXAM_START_DATEChanging(value);
					this.SendPropertyChanging();
					this._EXAM_START_DATE = value;
					this.SendPropertyChanged("EXAM_START_DATE");
					this.OnEXAM_START_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_LOCKED", DbType="Int NOT NULL")]
		public int IS_LOCKED
		{
			get
			{
				return this._IS_LOCKED;
			}
			set
			{
				if ((this._IS_LOCKED != value))
				{
					this.OnIS_LOCKEDChanging(value);
					this.SendPropertyChanging();
					this._IS_LOCKED = value;
					this.SendPropertyChanged("IS_LOCKED");
					this.OnIS_LOCKEDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="cpmd.VW_TASKLIST_DETAIL")]
	public partial class VW_TASKLIST_DETAIL
	{
		
		private string _RECORD_ID;
		
		private string _TASK_ID;
		
		private string _NRP;
		
		private string _MODULE_ID;
		
		private string _MODULE_SUB_ID;
		
		private string _MODULE_SUB_NAME;
		
		private int _STEP;
		
		private int _IS_LOCKED;
		
		private int _DURATION_MINUTE;
		
		private System.DateTime _REGISTRATION_DATE;
		
		private double _EXAM_SCORE;
		
		private byte _EXAM_STATUS;
		
		private string _SUPPORT_LINK;
		
		private System.Nullable<double> _PERCENT_COMPLETE;
		
		private System.Nullable<double> _REMINDING_TIME;
		
		private System.Nullable<System.DateTime> _UPDATE_REMINDING_TIME;
		
		private string _EXAM_START_DATE;
		
		public VW_TASKLIST_DETAIL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECORD_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RECORD_ID
		{
			get
			{
				return this._RECORD_ID;
			}
			set
			{
				if ((this._RECORD_ID != value))
				{
					this._RECORD_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TASK_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TASK_ID
		{
			get
			{
				return this._TASK_ID;
			}
			set
			{
				if ((this._TASK_ID != value))
				{
					this._TASK_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this._NRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE_ID", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MODULE_ID
		{
			get
			{
				return this._MODULE_ID;
			}
			set
			{
				if ((this._MODULE_ID != value))
				{
					this._MODULE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE_SUB_ID", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MODULE_SUB_ID
		{
			get
			{
				return this._MODULE_SUB_ID;
			}
			set
			{
				if ((this._MODULE_SUB_ID != value))
				{
					this._MODULE_SUB_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE_SUB_NAME", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string MODULE_SUB_NAME
		{
			get
			{
				return this._MODULE_SUB_NAME;
			}
			set
			{
				if ((this._MODULE_SUB_NAME != value))
				{
					this._MODULE_SUB_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STEP", DbType="Int NOT NULL")]
		public int STEP
		{
			get
			{
				return this._STEP;
			}
			set
			{
				if ((this._STEP != value))
				{
					this._STEP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_LOCKED", DbType="Int NOT NULL")]
		public int IS_LOCKED
		{
			get
			{
				return this._IS_LOCKED;
			}
			set
			{
				if ((this._IS_LOCKED != value))
				{
					this._IS_LOCKED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DURATION_MINUTE", DbType="Int NOT NULL")]
		public int DURATION_MINUTE
		{
			get
			{
				return this._DURATION_MINUTE;
			}
			set
			{
				if ((this._DURATION_MINUTE != value))
				{
					this._DURATION_MINUTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REGISTRATION_DATE", DbType="Date NOT NULL")]
		public System.DateTime REGISTRATION_DATE
		{
			get
			{
				return this._REGISTRATION_DATE;
			}
			set
			{
				if ((this._REGISTRATION_DATE != value))
				{
					this._REGISTRATION_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXAM_SCORE", DbType="Float NOT NULL")]
		public double EXAM_SCORE
		{
			get
			{
				return this._EXAM_SCORE;
			}
			set
			{
				if ((this._EXAM_SCORE != value))
				{
					this._EXAM_SCORE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXAM_STATUS", DbType="TinyInt NOT NULL")]
		public byte EXAM_STATUS
		{
			get
			{
				return this._EXAM_STATUS;
			}
			set
			{
				if ((this._EXAM_STATUS != value))
				{
					this._EXAM_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUPPORT_LINK", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string SUPPORT_LINK
		{
			get
			{
				return this._SUPPORT_LINK;
			}
			set
			{
				if ((this._SUPPORT_LINK != value))
				{
					this._SUPPORT_LINK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERCENT_COMPLETE", DbType="Float")]
		public System.Nullable<double> PERCENT_COMPLETE
		{
			get
			{
				return this._PERCENT_COMPLETE;
			}
			set
			{
				if ((this._PERCENT_COMPLETE != value))
				{
					this._PERCENT_COMPLETE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REMINDING_TIME", DbType="Float")]
		public System.Nullable<double> REMINDING_TIME
		{
			get
			{
				return this._REMINDING_TIME;
			}
			set
			{
				if ((this._REMINDING_TIME != value))
				{
					this._REMINDING_TIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATE_REMINDING_TIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATE_REMINDING_TIME
		{
			get
			{
				return this._UPDATE_REMINDING_TIME;
			}
			set
			{
				if ((this._UPDATE_REMINDING_TIME != value))
				{
					this._UPDATE_REMINDING_TIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXAM_START_DATE", DbType="VarChar(40)")]
		public string EXAM_START_DATE
		{
			get
			{
				return this._EXAM_START_DATE;
			}
			set
			{
				if ((this._EXAM_START_DATE != value))
				{
					this._EXAM_START_DATE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="cpmd.TBL_T_USER_ANSWER")]
	public partial class TBL_T_USER_ANSWER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int @__NO;
		
		private string _QA_ID;
		
		private string _TASK_ID;
		
		private string _NRP;
		
		private string _QUESTION_ID;
		
		private string _ANSWER_USER;
		
		private System.Nullable<bool> _STATUS;
		
		private System.Nullable<double> _SCORE;
		
		private int _JENIS_SOAL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On_NOChanging(int value);
    partial void On_NOChanged();
    partial void OnQA_IDChanging(string value);
    partial void OnQA_IDChanged();
    partial void OnTASK_IDChanging(string value);
    partial void OnTASK_IDChanged();
    partial void OnNRPChanging(string value);
    partial void OnNRPChanged();
    partial void OnQUESTION_IDChanging(string value);
    partial void OnQUESTION_IDChanged();
    partial void OnANSWER_USERChanging(string value);
    partial void OnANSWER_USERChanged();
    partial void OnSTATUSChanging(System.Nullable<bool> value);
    partial void OnSTATUSChanged();
    partial void OnSCOREChanging(System.Nullable<double> value);
    partial void OnSCOREChanged();
    partial void OnJENIS_SOALChanging(int value);
    partial void OnJENIS_SOALChanged();
    #endregion
		
		public TBL_T_USER_ANSWER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_NO]", Storage="__NO", DbType="Int NOT NULL")]
		public int _NO
		{
			get
			{
				return this.@__NO;
			}
			set
			{
				if ((this.@__NO != value))
				{
					this.On_NOChanging(value);
					this.SendPropertyChanging();
					this.@__NO = value;
					this.SendPropertyChanged("_NO");
					this.On_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QA_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string QA_ID
		{
			get
			{
				return this._QA_ID;
			}
			set
			{
				if ((this._QA_ID != value))
				{
					this.OnQA_IDChanging(value);
					this.SendPropertyChanging();
					this._QA_ID = value;
					this.SendPropertyChanged("QA_ID");
					this.OnQA_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TASK_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TASK_ID
		{
			get
			{
				return this._TASK_ID;
			}
			set
			{
				if ((this._TASK_ID != value))
				{
					this.OnTASK_IDChanging(value);
					this.SendPropertyChanging();
					this._TASK_ID = value;
					this.SendPropertyChanged("TASK_ID");
					this.OnTASK_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this.OnNRPChanging(value);
					this.SendPropertyChanging();
					this._NRP = value;
					this.SendPropertyChanged("NRP");
					this.OnNRPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUESTION_ID", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string QUESTION_ID
		{
			get
			{
				return this._QUESTION_ID;
			}
			set
			{
				if ((this._QUESTION_ID != value))
				{
					this.OnQUESTION_IDChanging(value);
					this.SendPropertyChanging();
					this._QUESTION_ID = value;
					this.SendPropertyChanged("QUESTION_ID");
					this.OnQUESTION_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANSWER_USER", DbType="VarChar(MAX)")]
		public string ANSWER_USER
		{
			get
			{
				return this._ANSWER_USER;
			}
			set
			{
				if ((this._ANSWER_USER != value))
				{
					this.OnANSWER_USERChanging(value);
					this.SendPropertyChanging();
					this._ANSWER_USER = value;
					this.SendPropertyChanged("ANSWER_USER");
					this.OnANSWER_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Bit")]
		public System.Nullable<bool> STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCORE", DbType="Float")]
		public System.Nullable<double> SCORE
		{
			get
			{
				return this._SCORE;
			}
			set
			{
				if ((this._SCORE != value))
				{
					this.OnSCOREChanging(value);
					this.SendPropertyChanging();
					this._SCORE = value;
					this.SendPropertyChanged("SCORE");
					this.OnSCOREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JENIS_SOAL", DbType="Int NOT NULL")]
		public int JENIS_SOAL
		{
			get
			{
				return this._JENIS_SOAL;
			}
			set
			{
				if ((this._JENIS_SOAL != value))
				{
					this.OnJENIS_SOALChanging(value);
					this.SendPropertyChanging();
					this._JENIS_SOAL = value;
					this.SendPropertyChanged("JENIS_SOAL");
					this.OnJENIS_SOALChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="cpmd.TBL_R_COMPETENCY")]
	public partial class TBL_R_COMPETENCY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MODULE_SUB_ID;
		
		private string _MODULE_SUB_NAME;
		
		private string _MODULE_ID;
		
		private int _STEP;
		
		private int _IS_LAST_COMPETENCY;
		
		private System.Nullable<int> _SI_ACTIVE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMODULE_SUB_IDChanging(string value);
    partial void OnMODULE_SUB_IDChanged();
    partial void OnMODULE_SUB_NAMEChanging(string value);
    partial void OnMODULE_SUB_NAMEChanged();
    partial void OnMODULE_IDChanging(string value);
    partial void OnMODULE_IDChanged();
    partial void OnSTEPChanging(int value);
    partial void OnSTEPChanged();
    partial void OnIS_LAST_COMPETENCYChanging(int value);
    partial void OnIS_LAST_COMPETENCYChanged();
    partial void OnSI_ACTIVEChanging(System.Nullable<int> value);
    partial void OnSI_ACTIVEChanged();
    #endregion
		
		public TBL_R_COMPETENCY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE_SUB_ID", DbType="Char(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MODULE_SUB_ID
		{
			get
			{
				return this._MODULE_SUB_ID;
			}
			set
			{
				if ((this._MODULE_SUB_ID != value))
				{
					this.OnMODULE_SUB_IDChanging(value);
					this.SendPropertyChanging();
					this._MODULE_SUB_ID = value;
					this.SendPropertyChanged("MODULE_SUB_ID");
					this.OnMODULE_SUB_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE_SUB_NAME", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string MODULE_SUB_NAME
		{
			get
			{
				return this._MODULE_SUB_NAME;
			}
			set
			{
				if ((this._MODULE_SUB_NAME != value))
				{
					this.OnMODULE_SUB_NAMEChanging(value);
					this.SendPropertyChanging();
					this._MODULE_SUB_NAME = value;
					this.SendPropertyChanged("MODULE_SUB_NAME");
					this.OnMODULE_SUB_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE_ID", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MODULE_ID
		{
			get
			{
				return this._MODULE_ID;
			}
			set
			{
				if ((this._MODULE_ID != value))
				{
					this.OnMODULE_IDChanging(value);
					this.SendPropertyChanging();
					this._MODULE_ID = value;
					this.SendPropertyChanged("MODULE_ID");
					this.OnMODULE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STEP", DbType="Int NOT NULL")]
		public int STEP
		{
			get
			{
				return this._STEP;
			}
			set
			{
				if ((this._STEP != value))
				{
					this.OnSTEPChanging(value);
					this.SendPropertyChanging();
					this._STEP = value;
					this.SendPropertyChanged("STEP");
					this.OnSTEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_LAST_COMPETENCY", DbType="Int NOT NULL")]
		public int IS_LAST_COMPETENCY
		{
			get
			{
				return this._IS_LAST_COMPETENCY;
			}
			set
			{
				if ((this._IS_LAST_COMPETENCY != value))
				{
					this.OnIS_LAST_COMPETENCYChanging(value);
					this.SendPropertyChanging();
					this._IS_LAST_COMPETENCY = value;
					this.SendPropertyChanged("IS_LAST_COMPETENCY");
					this.OnIS_LAST_COMPETENCYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SI_ACTIVE", DbType="Int")]
		public System.Nullable<int> SI_ACTIVE
		{
			get
			{
				return this._SI_ACTIVE;
			}
			set
			{
				if ((this._SI_ACTIVE != value))
				{
					this.OnSI_ACTIVEChanging(value);
					this.SendPropertyChanging();
					this._SI_ACTIVE = value;
					this.SendPropertyChanged("SI_ACTIVE");
					this.OnSI_ACTIVEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="ocel.VW_R_MODULE")]
	public partial class VW_R_MODULE
	{
		
		private string _MODULE_ID;
		
		private string _MODULE_NAME;
		
		private System.Nullable<int> _IS_ACTIVE;
		
		public VW_R_MODULE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE_ID", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MODULE_ID
		{
			get
			{
				return this._MODULE_ID;
			}
			set
			{
				if ((this._MODULE_ID != value))
				{
					this._MODULE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE_NAME", DbType="VarChar(250)")]
		public string MODULE_NAME
		{
			get
			{
				return this._MODULE_NAME;
			}
			set
			{
				if ((this._MODULE_NAME != value))
				{
					this._MODULE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_ACTIVE", DbType="Int")]
		public System.Nullable<int> IS_ACTIVE
		{
			get
			{
				return this._IS_ACTIVE;
			}
			set
			{
				if ((this._IS_ACTIVE != value))
				{
					this._IS_ACTIVE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="cpmd.TBL_R_MODULE_CLASS")]
	public partial class TBL_R_MODULE_CLASS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MODULE_ID;
		
		private string _MODULE_NAME;
		
		private System.Nullable<int> _IS_ACTIVE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMODULE_IDChanging(string value);
    partial void OnMODULE_IDChanged();
    partial void OnMODULE_NAMEChanging(string value);
    partial void OnMODULE_NAMEChanged();
    partial void OnIS_ACTIVEChanging(System.Nullable<int> value);
    partial void OnIS_ACTIVEChanged();
    #endregion
		
		public TBL_R_MODULE_CLASS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE_ID", DbType="Char(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MODULE_ID
		{
			get
			{
				return this._MODULE_ID;
			}
			set
			{
				if ((this._MODULE_ID != value))
				{
					this.OnMODULE_IDChanging(value);
					this.SendPropertyChanging();
					this._MODULE_ID = value;
					this.SendPropertyChanged("MODULE_ID");
					this.OnMODULE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE_NAME", DbType="VarChar(250)")]
		public string MODULE_NAME
		{
			get
			{
				return this._MODULE_NAME;
			}
			set
			{
				if ((this._MODULE_NAME != value))
				{
					this.OnMODULE_NAMEChanging(value);
					this.SendPropertyChanging();
					this._MODULE_NAME = value;
					this.SendPropertyChanged("MODULE_NAME");
					this.OnMODULE_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_ACTIVE", DbType="Int")]
		public System.Nullable<int> IS_ACTIVE
		{
			get
			{
				return this._IS_ACTIVE;
			}
			set
			{
				if ((this._IS_ACTIVE != value))
				{
					this.OnIS_ACTIVEChanging(value);
					this.SendPropertyChanging();
					this._IS_ACTIVE = value;
					this.SendPropertyChanged("IS_ACTIVE");
					this.OnIS_ACTIVEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="ocel.VW_R_SUB_MODULE")]
	public partial class VW_R_SUB_MODULE
	{
		
		private string _MODULE_SUB_ID;
		
		private string _MODULE_SUB_NAME;
		
		private string _MODULE_ID;
		
		private string _MODULE_NAME;
		
		private int _STEP;
		
		private int _IS_LAST_COMPETENCY;
		
		private System.Nullable<int> _SI_ACTIVE;
		
		public VW_R_SUB_MODULE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE_SUB_ID", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MODULE_SUB_ID
		{
			get
			{
				return this._MODULE_SUB_ID;
			}
			set
			{
				if ((this._MODULE_SUB_ID != value))
				{
					this._MODULE_SUB_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE_SUB_NAME", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string MODULE_SUB_NAME
		{
			get
			{
				return this._MODULE_SUB_NAME;
			}
			set
			{
				if ((this._MODULE_SUB_NAME != value))
				{
					this._MODULE_SUB_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE_ID", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MODULE_ID
		{
			get
			{
				return this._MODULE_ID;
			}
			set
			{
				if ((this._MODULE_ID != value))
				{
					this._MODULE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE_NAME", DbType="VarChar(250)")]
		public string MODULE_NAME
		{
			get
			{
				return this._MODULE_NAME;
			}
			set
			{
				if ((this._MODULE_NAME != value))
				{
					this._MODULE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STEP", DbType="Int NOT NULL")]
		public int STEP
		{
			get
			{
				return this._STEP;
			}
			set
			{
				if ((this._STEP != value))
				{
					this._STEP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_LAST_COMPETENCY", DbType="Int NOT NULL")]
		public int IS_LAST_COMPETENCY
		{
			get
			{
				return this._IS_LAST_COMPETENCY;
			}
			set
			{
				if ((this._IS_LAST_COMPETENCY != value))
				{
					this._IS_LAST_COMPETENCY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SI_ACTIVE", DbType="Int")]
		public System.Nullable<int> SI_ACTIVE
		{
			get
			{
				return this._SI_ACTIVE;
			}
			set
			{
				if ((this._SI_ACTIVE != value))
				{
					this._SI_ACTIVE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="cpmd.VW_T_READING_REPORT")]
	public partial class VW_T_READING_REPORT
	{
		
		private string _TASK_ID;
		
		private string _MODULE_ID;
		
		private string _MODULE_NAME;
		
		private string _NRP;
		
		private string _NAME;
		
		private string _DSTRCT_CODE;
		
		private string _DEPARTEMENT;
		
		private string _DIVISION;
		
		private string _POS_TITLE;
		
		private System.Nullable<System.DateTime> _EXAM_FINISH_TIME;
		
		public VW_T_READING_REPORT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TASK_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TASK_ID
		{
			get
			{
				return this._TASK_ID;
			}
			set
			{
				if ((this._TASK_ID != value))
				{
					this._TASK_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE_ID", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MODULE_ID
		{
			get
			{
				return this._MODULE_ID;
			}
			set
			{
				if ((this._MODULE_ID != value))
				{
					this._MODULE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE_NAME", DbType="VarChar(250)")]
		public string MODULE_NAME
		{
			get
			{
				return this._MODULE_NAME;
			}
			set
			{
				if ((this._MODULE_NAME != value))
				{
					this._MODULE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this._NRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(43)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(4)")]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this._DSTRCT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPARTEMENT", DbType="VarChar(50)")]
		public string DEPARTEMENT
		{
			get
			{
				return this._DEPARTEMENT;
			}
			set
			{
				if ((this._DEPARTEMENT != value))
				{
					this._DEPARTEMENT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIVISION", DbType="VarChar(50)")]
		public string DIVISION
		{
			get
			{
				return this._DIVISION;
			}
			set
			{
				if ((this._DIVISION != value))
				{
					this._DIVISION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POS_TITLE", DbType="VarChar(40)")]
		public string POS_TITLE
		{
			get
			{
				return this._POS_TITLE;
			}
			set
			{
				if ((this._POS_TITLE != value))
				{
					this._POS_TITLE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXAM_FINISH_TIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> EXAM_FINISH_TIME
		{
			get
			{
				return this._EXAM_FINISH_TIME;
			}
			set
			{
				if ((this._EXAM_FINISH_TIME != value))
				{
					this._EXAM_FINISH_TIME = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="cpmd.TBL_MODULE_SET")]
	public partial class TBL_MODULE_SET : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _T_PID;
		
		private string _MODULE_ID;
		
		private byte _QUESTION_TYPE;
		
		private int _PRIORITY;
		
		private System.DateTime _create_date;
		
		private string _create_by;
		
		private int _QUESTION_EACH_COMPETENCY;
		
		private int _DURATION_MINUTE;
		
		private int _PASSING_GRADE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnT_PIDChanging(string value);
    partial void OnT_PIDChanged();
    partial void OnMODULE_IDChanging(string value);
    partial void OnMODULE_IDChanged();
    partial void OnQUESTION_TYPEChanging(byte value);
    partial void OnQUESTION_TYPEChanged();
    partial void OnPRIORITYChanging(int value);
    partial void OnPRIORITYChanged();
    partial void Oncreate_dateChanging(System.DateTime value);
    partial void Oncreate_dateChanged();
    partial void Oncreate_byChanging(string value);
    partial void Oncreate_byChanged();
    partial void OnQUESTION_EACH_COMPETENCYChanging(int value);
    partial void OnQUESTION_EACH_COMPETENCYChanged();
    partial void OnDURATION_MINUTEChanging(int value);
    partial void OnDURATION_MINUTEChanged();
    partial void OnPASSING_GRADEChanging(int value);
    partial void OnPASSING_GRADEChanged();
    #endregion
		
		public TBL_MODULE_SET()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_PID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string T_PID
		{
			get
			{
				return this._T_PID;
			}
			set
			{
				if ((this._T_PID != value))
				{
					this.OnT_PIDChanging(value);
					this.SendPropertyChanging();
					this._T_PID = value;
					this.SendPropertyChanged("T_PID");
					this.OnT_PIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE_ID", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MODULE_ID
		{
			get
			{
				return this._MODULE_ID;
			}
			set
			{
				if ((this._MODULE_ID != value))
				{
					this.OnMODULE_IDChanging(value);
					this.SendPropertyChanging();
					this._MODULE_ID = value;
					this.SendPropertyChanged("MODULE_ID");
					this.OnMODULE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUESTION_TYPE", DbType="TinyInt NOT NULL")]
		public byte QUESTION_TYPE
		{
			get
			{
				return this._QUESTION_TYPE;
			}
			set
			{
				if ((this._QUESTION_TYPE != value))
				{
					this.OnQUESTION_TYPEChanging(value);
					this.SendPropertyChanging();
					this._QUESTION_TYPE = value;
					this.SendPropertyChanged("QUESTION_TYPE");
					this.OnQUESTION_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIORITY", DbType="Int NOT NULL")]
		public int PRIORITY
		{
			get
			{
				return this._PRIORITY;
			}
			set
			{
				if ((this._PRIORITY != value))
				{
					this.OnPRIORITYChanging(value);
					this.SendPropertyChanging();
					this._PRIORITY = value;
					this.SendPropertyChanged("PRIORITY");
					this.OnPRIORITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this.Oncreate_dateChanging(value);
					this.SendPropertyChanging();
					this._create_date = value;
					this.SendPropertyChanged("create_date");
					this.Oncreate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_by", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string create_by
		{
			get
			{
				return this._create_by;
			}
			set
			{
				if ((this._create_by != value))
				{
					this.Oncreate_byChanging(value);
					this.SendPropertyChanging();
					this._create_by = value;
					this.SendPropertyChanged("create_by");
					this.Oncreate_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUESTION_EACH_COMPETENCY", DbType="Int NOT NULL")]
		public int QUESTION_EACH_COMPETENCY
		{
			get
			{
				return this._QUESTION_EACH_COMPETENCY;
			}
			set
			{
				if ((this._QUESTION_EACH_COMPETENCY != value))
				{
					this.OnQUESTION_EACH_COMPETENCYChanging(value);
					this.SendPropertyChanging();
					this._QUESTION_EACH_COMPETENCY = value;
					this.SendPropertyChanged("QUESTION_EACH_COMPETENCY");
					this.OnQUESTION_EACH_COMPETENCYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DURATION_MINUTE", DbType="Int NOT NULL")]
		public int DURATION_MINUTE
		{
			get
			{
				return this._DURATION_MINUTE;
			}
			set
			{
				if ((this._DURATION_MINUTE != value))
				{
					this.OnDURATION_MINUTEChanging(value);
					this.SendPropertyChanging();
					this._DURATION_MINUTE = value;
					this.SendPropertyChanged("DURATION_MINUTE");
					this.OnDURATION_MINUTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSING_GRADE", DbType="Int NOT NULL")]
		public int PASSING_GRADE
		{
			get
			{
				return this._PASSING_GRADE;
			}
			set
			{
				if ((this._PASSING_GRADE != value))
				{
					this.OnPASSING_GRADEChanging(value);
					this.SendPropertyChanging();
					this._PASSING_GRADE = value;
					this.SendPropertyChanged("PASSING_GRADE");
					this.OnPASSING_GRADEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="ocel.VW_T_MODULE_SET")]
	public partial class VW_T_MODULE_SET
	{
		
		private string _T_PID;
		
		private string _MODULE_ID;
		
		private string _MODULE_NAME;
		
		private byte _QUESTION_TYPE;
		
		private string _TYPE_DESC;
		
		private int _PRIORITY;
		
		private System.DateTime _create_date;
		
		private string _create_by;
		
		private int _QUESTION_EACH_COMPETENCY;
		
		private int _DURATION_MINUTE;
		
		private int _PASSING_GRADE;
		
		public VW_T_MODULE_SET()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_PID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string T_PID
		{
			get
			{
				return this._T_PID;
			}
			set
			{
				if ((this._T_PID != value))
				{
					this._T_PID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE_ID", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string MODULE_ID
		{
			get
			{
				return this._MODULE_ID;
			}
			set
			{
				if ((this._MODULE_ID != value))
				{
					this._MODULE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE_NAME", DbType="VarChar(250)")]
		public string MODULE_NAME
		{
			get
			{
				return this._MODULE_NAME;
			}
			set
			{
				if ((this._MODULE_NAME != value))
				{
					this._MODULE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUESTION_TYPE", DbType="TinyInt NOT NULL")]
		public byte QUESTION_TYPE
		{
			get
			{
				return this._QUESTION_TYPE;
			}
			set
			{
				if ((this._QUESTION_TYPE != value))
				{
					this._QUESTION_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYPE_DESC", DbType="VarChar(50)")]
		public string TYPE_DESC
		{
			get
			{
				return this._TYPE_DESC;
			}
			set
			{
				if ((this._TYPE_DESC != value))
				{
					this._TYPE_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIORITY", DbType="Int NOT NULL")]
		public int PRIORITY
		{
			get
			{
				return this._PRIORITY;
			}
			set
			{
				if ((this._PRIORITY != value))
				{
					this._PRIORITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this._create_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_by", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string create_by
		{
			get
			{
				return this._create_by;
			}
			set
			{
				if ((this._create_by != value))
				{
					this._create_by = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUESTION_EACH_COMPETENCY", DbType="Int NOT NULL")]
		public int QUESTION_EACH_COMPETENCY
		{
			get
			{
				return this._QUESTION_EACH_COMPETENCY;
			}
			set
			{
				if ((this._QUESTION_EACH_COMPETENCY != value))
				{
					this._QUESTION_EACH_COMPETENCY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DURATION_MINUTE", DbType="Int NOT NULL")]
		public int DURATION_MINUTE
		{
			get
			{
				return this._DURATION_MINUTE;
			}
			set
			{
				if ((this._DURATION_MINUTE != value))
				{
					this._DURATION_MINUTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSING_GRADE", DbType="Int NOT NULL")]
		public int PASSING_GRADE
		{
			get
			{
				return this._PASSING_GRADE;
			}
			set
			{
				if ((this._PASSING_GRADE != value))
				{
					this._PASSING_GRADE = value;
				}
			}
		}
	}
	
	public partial class GetMyTaskListResult
	{
		
		private string _TASK_ID;
		
		private string _NRP;
		
		private string _MODULE_ID;
		
		private string _MODULE_NAME;
		
		private string _ASSIGN_DIV;
		
		private System.DateTime _ASSIGN_DATE;
		
		private System.Nullable<int> _TASK_COUNT;
		
		private System.Nullable<int> _J_UNLOCK;
		
		private string _TASK_STATUS;
		
		private string _BTN_ENABLER;
		
		public GetMyTaskListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TASK_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TASK_ID
		{
			get
			{
				return this._TASK_ID;
			}
			set
			{
				if ((this._TASK_ID != value))
				{
					this._TASK_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this._NRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE_ID", DbType="Char(2)")]
		public string MODULE_ID
		{
			get
			{
				return this._MODULE_ID;
			}
			set
			{
				if ((this._MODULE_ID != value))
				{
					this._MODULE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE_NAME", DbType="VarChar(250)")]
		public string MODULE_NAME
		{
			get
			{
				return this._MODULE_NAME;
			}
			set
			{
				if ((this._MODULE_NAME != value))
				{
					this._MODULE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASSIGN_DIV", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string ASSIGN_DIV
		{
			get
			{
				return this._ASSIGN_DIV;
			}
			set
			{
				if ((this._ASSIGN_DIV != value))
				{
					this._ASSIGN_DIV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASSIGN_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime ASSIGN_DATE
		{
			get
			{
				return this._ASSIGN_DATE;
			}
			set
			{
				if ((this._ASSIGN_DATE != value))
				{
					this._ASSIGN_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TASK_COUNT", DbType="Int")]
		public System.Nullable<int> TASK_COUNT
		{
			get
			{
				return this._TASK_COUNT;
			}
			set
			{
				if ((this._TASK_COUNT != value))
				{
					this._TASK_COUNT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_J_UNLOCK", DbType="Int")]
		public System.Nullable<int> J_UNLOCK
		{
			get
			{
				return this._J_UNLOCK;
			}
			set
			{
				if ((this._J_UNLOCK != value))
				{
					this._J_UNLOCK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TASK_STATUS", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string TASK_STATUS
		{
			get
			{
				return this._TASK_STATUS;
			}
			set
			{
				if ((this._TASK_STATUS != value))
				{
					this._TASK_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BTN_ENABLER", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string BTN_ENABLER
		{
			get
			{
				return this._BTN_ENABLER;
			}
			set
			{
				if ((this._BTN_ENABLER != value))
				{
					this._BTN_ENABLER = value;
				}
			}
		}
	}
	
	public partial class cufn_get_taskList_detailResult
	{
		
		private string _RECORD_ID;
		
		private string _TASK_ID;
		
		private string _MODULE_SUB_NAME;
		
		private int _STEP;
		
		private int _IS_LOCKED;
		
		private int _DURATION_MINUTE;
		
		private System.DateTime _REGISTRATION_DATE;
		
		private double _EXAM_SCORE;
		
		private byte _EXAM_STATUS;
		
		private string _SUPPORT_LINK;
		
		private System.Nullable<double> _PERCENT_COMPLETE;
		
		private System.Nullable<double> _REMINDING_TIME;
		
		private System.Nullable<System.DateTime> _UPDATE_REMINDING_TIME;
		
		private string _EXAM_START_DATE;
		
		public cufn_get_taskList_detailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECORD_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RECORD_ID
		{
			get
			{
				return this._RECORD_ID;
			}
			set
			{
				if ((this._RECORD_ID != value))
				{
					this._RECORD_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TASK_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TASK_ID
		{
			get
			{
				return this._TASK_ID;
			}
			set
			{
				if ((this._TASK_ID != value))
				{
					this._TASK_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE_SUB_NAME", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string MODULE_SUB_NAME
		{
			get
			{
				return this._MODULE_SUB_NAME;
			}
			set
			{
				if ((this._MODULE_SUB_NAME != value))
				{
					this._MODULE_SUB_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STEP", DbType="Int NOT NULL")]
		public int STEP
		{
			get
			{
				return this._STEP;
			}
			set
			{
				if ((this._STEP != value))
				{
					this._STEP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_LOCKED", DbType="Int NOT NULL")]
		public int IS_LOCKED
		{
			get
			{
				return this._IS_LOCKED;
			}
			set
			{
				if ((this._IS_LOCKED != value))
				{
					this._IS_LOCKED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DURATION_MINUTE", DbType="Int NOT NULL")]
		public int DURATION_MINUTE
		{
			get
			{
				return this._DURATION_MINUTE;
			}
			set
			{
				if ((this._DURATION_MINUTE != value))
				{
					this._DURATION_MINUTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REGISTRATION_DATE", DbType="Date NOT NULL")]
		public System.DateTime REGISTRATION_DATE
		{
			get
			{
				return this._REGISTRATION_DATE;
			}
			set
			{
				if ((this._REGISTRATION_DATE != value))
				{
					this._REGISTRATION_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXAM_SCORE", DbType="Float NOT NULL")]
		public double EXAM_SCORE
		{
			get
			{
				return this._EXAM_SCORE;
			}
			set
			{
				if ((this._EXAM_SCORE != value))
				{
					this._EXAM_SCORE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXAM_STATUS", DbType="TinyInt NOT NULL")]
		public byte EXAM_STATUS
		{
			get
			{
				return this._EXAM_STATUS;
			}
			set
			{
				if ((this._EXAM_STATUS != value))
				{
					this._EXAM_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUPPORT_LINK", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string SUPPORT_LINK
		{
			get
			{
				return this._SUPPORT_LINK;
			}
			set
			{
				if ((this._SUPPORT_LINK != value))
				{
					this._SUPPORT_LINK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERCENT_COMPLETE", DbType="Float")]
		public System.Nullable<double> PERCENT_COMPLETE
		{
			get
			{
				return this._PERCENT_COMPLETE;
			}
			set
			{
				if ((this._PERCENT_COMPLETE != value))
				{
					this._PERCENT_COMPLETE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REMINDING_TIME", DbType="Float")]
		public System.Nullable<double> REMINDING_TIME
		{
			get
			{
				return this._REMINDING_TIME;
			}
			set
			{
				if ((this._REMINDING_TIME != value))
				{
					this._REMINDING_TIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATE_REMINDING_TIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATE_REMINDING_TIME
		{
			get
			{
				return this._UPDATE_REMINDING_TIME;
			}
			set
			{
				if ((this._UPDATE_REMINDING_TIME != value))
				{
					this._UPDATE_REMINDING_TIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXAM_START_DATE", DbType="VarChar(40)")]
		public string EXAM_START_DATE
		{
			get
			{
				return this._EXAM_START_DATE;
			}
			set
			{
				if ((this._EXAM_START_DATE != value))
				{
					this._EXAM_START_DATE = value;
				}
			}
		}
	}
	
	public partial class cusp_generate_soal_acakResult
	{
		
		private string _QA_ID;
		
		private string _REGISTRATION_ID;
		
		private string _NRP;
		
		private string _QUESTION_ID;
		
		private string _ANSWER_USER;
		
		private System.Nullable<bool> _STATUS;
		
		private System.Nullable<double> _SCORE;
		
		private int _JENIS_SOAL;
		
		public cusp_generate_soal_acakResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QA_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string QA_ID
		{
			get
			{
				return this._QA_ID;
			}
			set
			{
				if ((this._QA_ID != value))
				{
					this._QA_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REGISTRATION_ID", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string REGISTRATION_ID
		{
			get
			{
				return this._REGISTRATION_ID;
			}
			set
			{
				if ((this._REGISTRATION_ID != value))
				{
					this._REGISTRATION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this._NRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUESTION_ID", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string QUESTION_ID
		{
			get
			{
				return this._QUESTION_ID;
			}
			set
			{
				if ((this._QUESTION_ID != value))
				{
					this._QUESTION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANSWER_USER", DbType="VarChar(MAX)")]
		public string ANSWER_USER
		{
			get
			{
				return this._ANSWER_USER;
			}
			set
			{
				if ((this._ANSWER_USER != value))
				{
					this._ANSWER_USER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="Bit")]
		public System.Nullable<bool> STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this._STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCORE", DbType="Float")]
		public System.Nullable<double> SCORE
		{
			get
			{
				return this._SCORE;
			}
			set
			{
				if ((this._SCORE != value))
				{
					this._SCORE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JENIS_SOAL", DbType="Int NOT NULL")]
		public int JENIS_SOAL
		{
			get
			{
				return this._JENIS_SOAL;
			}
			set
			{
				if ((this._JENIS_SOAL != value))
				{
					this._JENIS_SOAL = value;
				}
			}
		}
	}
	
	public partial class cufn_get_list_detailResult
	{
		
		private string _RECORD_ID;
		
		private string _TASK_ID;
		
		private string _STUDENT_ID;
		
		private string _DSTRCT_CODE;
		
		private string _DEPARTMENT;
		
		private int _PERIOD;
		
		private string _POSITION_CODE;
		
		private string _POSITION_DESC;
		
		private int _NUMBER_OF_QUESTION;
		
		private System.Nullable<int> _DURATION_MINUTE;
		
		private System.Nullable<double> _PASSING_GRADE_PERCENT;
		
		private System.Nullable<bool> _RANDOMIZED_ANSWER;
		
		private System.DateTime _REGISTRATION_DATE;
		
		private string _EXAM_ACTUAL_DATE;
		
		private System.Nullable<System.DateTime> _EXAM_LOGIN_TIME;
		
		private System.Nullable<System.DateTime> _EXAM_FINISH_TIME;
		
		private string _EXAM_COMP_ID;
		
		private System.Nullable<byte> _EXAM_STATUS;
		
		private System.Nullable<double> _EXAM_SCORE;
		
		private System.Nullable<double> _PERCENT_COMPLETE;
		
		private System.Nullable<double> _REMINDING_TIME;
		
		private System.Nullable<System.DateTime> _UPDATE_REMINDING_TIME;
		
		private string _EXAM_START_DATE;
		
		private System.Nullable<int> _QUESTION_TYPE;
		
		private string _JENIS_SOAL;
		
		private string _SUB_MODULE_ID;
		
		private int _EXAM_TYPE;
		
		private int _IS_LOCKED;
		
		private string _MODULE_NAME;
		
		public cufn_get_list_detailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECORD_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RECORD_ID
		{
			get
			{
				return this._RECORD_ID;
			}
			set
			{
				if ((this._RECORD_ID != value))
				{
					this._RECORD_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TASK_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TASK_ID
		{
			get
			{
				return this._TASK_ID;
			}
			set
			{
				if ((this._TASK_ID != value))
				{
					this._TASK_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STUDENT_ID", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string STUDENT_ID
		{
			get
			{
				return this._STUDENT_ID;
			}
			set
			{
				if ((this._STUDENT_ID != value))
				{
					this._STUDENT_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this._DSTRCT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPARTMENT", DbType="VarChar(250)")]
		public string DEPARTMENT
		{
			get
			{
				return this._DEPARTMENT;
			}
			set
			{
				if ((this._DEPARTMENT != value))
				{
					this._DEPARTMENT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERIOD", DbType="Int NOT NULL")]
		public int PERIOD
		{
			get
			{
				return this._PERIOD;
			}
			set
			{
				if ((this._PERIOD != value))
				{
					this._PERIOD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_CODE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string POSITION_CODE
		{
			get
			{
				return this._POSITION_CODE;
			}
			set
			{
				if ((this._POSITION_CODE != value))
				{
					this._POSITION_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_DESC", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string POSITION_DESC
		{
			get
			{
				return this._POSITION_DESC;
			}
			set
			{
				if ((this._POSITION_DESC != value))
				{
					this._POSITION_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMBER_OF_QUESTION", DbType="Int NOT NULL")]
		public int NUMBER_OF_QUESTION
		{
			get
			{
				return this._NUMBER_OF_QUESTION;
			}
			set
			{
				if ((this._NUMBER_OF_QUESTION != value))
				{
					this._NUMBER_OF_QUESTION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DURATION_MINUTE", DbType="Int")]
		public System.Nullable<int> DURATION_MINUTE
		{
			get
			{
				return this._DURATION_MINUTE;
			}
			set
			{
				if ((this._DURATION_MINUTE != value))
				{
					this._DURATION_MINUTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSING_GRADE_PERCENT", DbType="Float")]
		public System.Nullable<double> PASSING_GRADE_PERCENT
		{
			get
			{
				return this._PASSING_GRADE_PERCENT;
			}
			set
			{
				if ((this._PASSING_GRADE_PERCENT != value))
				{
					this._PASSING_GRADE_PERCENT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RANDOMIZED_ANSWER", DbType="Bit")]
		public System.Nullable<bool> RANDOMIZED_ANSWER
		{
			get
			{
				return this._RANDOMIZED_ANSWER;
			}
			set
			{
				if ((this._RANDOMIZED_ANSWER != value))
				{
					this._RANDOMIZED_ANSWER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REGISTRATION_DATE", DbType="Date NOT NULL")]
		public System.DateTime REGISTRATION_DATE
		{
			get
			{
				return this._REGISTRATION_DATE;
			}
			set
			{
				if ((this._REGISTRATION_DATE != value))
				{
					this._REGISTRATION_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXAM_ACTUAL_DATE", DbType="VarChar(40)")]
		public string EXAM_ACTUAL_DATE
		{
			get
			{
				return this._EXAM_ACTUAL_DATE;
			}
			set
			{
				if ((this._EXAM_ACTUAL_DATE != value))
				{
					this._EXAM_ACTUAL_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXAM_LOGIN_TIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> EXAM_LOGIN_TIME
		{
			get
			{
				return this._EXAM_LOGIN_TIME;
			}
			set
			{
				if ((this._EXAM_LOGIN_TIME != value))
				{
					this._EXAM_LOGIN_TIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXAM_FINISH_TIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> EXAM_FINISH_TIME
		{
			get
			{
				return this._EXAM_FINISH_TIME;
			}
			set
			{
				if ((this._EXAM_FINISH_TIME != value))
				{
					this._EXAM_FINISH_TIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXAM_COMP_ID", DbType="VarChar(50)")]
		public string EXAM_COMP_ID
		{
			get
			{
				return this._EXAM_COMP_ID;
			}
			set
			{
				if ((this._EXAM_COMP_ID != value))
				{
					this._EXAM_COMP_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXAM_STATUS", DbType="TinyInt")]
		public System.Nullable<byte> EXAM_STATUS
		{
			get
			{
				return this._EXAM_STATUS;
			}
			set
			{
				if ((this._EXAM_STATUS != value))
				{
					this._EXAM_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXAM_SCORE", DbType="Float")]
		public System.Nullable<double> EXAM_SCORE
		{
			get
			{
				return this._EXAM_SCORE;
			}
			set
			{
				if ((this._EXAM_SCORE != value))
				{
					this._EXAM_SCORE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERCENT_COMPLETE", DbType="Float")]
		public System.Nullable<double> PERCENT_COMPLETE
		{
			get
			{
				return this._PERCENT_COMPLETE;
			}
			set
			{
				if ((this._PERCENT_COMPLETE != value))
				{
					this._PERCENT_COMPLETE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REMINDING_TIME", DbType="Float")]
		public System.Nullable<double> REMINDING_TIME
		{
			get
			{
				return this._REMINDING_TIME;
			}
			set
			{
				if ((this._REMINDING_TIME != value))
				{
					this._REMINDING_TIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATE_REMINDING_TIME", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATE_REMINDING_TIME
		{
			get
			{
				return this._UPDATE_REMINDING_TIME;
			}
			set
			{
				if ((this._UPDATE_REMINDING_TIME != value))
				{
					this._UPDATE_REMINDING_TIME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXAM_START_DATE", DbType="VarChar(40)")]
		public string EXAM_START_DATE
		{
			get
			{
				return this._EXAM_START_DATE;
			}
			set
			{
				if ((this._EXAM_START_DATE != value))
				{
					this._EXAM_START_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUESTION_TYPE", DbType="Int")]
		public System.Nullable<int> QUESTION_TYPE
		{
			get
			{
				return this._QUESTION_TYPE;
			}
			set
			{
				if ((this._QUESTION_TYPE != value))
				{
					this._QUESTION_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JENIS_SOAL", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string JENIS_SOAL
		{
			get
			{
				return this._JENIS_SOAL;
			}
			set
			{
				if ((this._JENIS_SOAL != value))
				{
					this._JENIS_SOAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_MODULE_ID", DbType="VarChar(3)")]
		public string SUB_MODULE_ID
		{
			get
			{
				return this._SUB_MODULE_ID;
			}
			set
			{
				if ((this._SUB_MODULE_ID != value))
				{
					this._SUB_MODULE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXAM_TYPE", DbType="Int NOT NULL")]
		public int EXAM_TYPE
		{
			get
			{
				return this._EXAM_TYPE;
			}
			set
			{
				if ((this._EXAM_TYPE != value))
				{
					this._EXAM_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_LOCKED", DbType="Int NOT NULL")]
		public int IS_LOCKED
		{
			get
			{
				return this._IS_LOCKED;
			}
			set
			{
				if ((this._IS_LOCKED != value))
				{
					this._IS_LOCKED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODULE_NAME", DbType="VarChar(250)")]
		public string MODULE_NAME
		{
			get
			{
				return this._MODULE_NAME;
			}
			set
			{
				if ((this._MODULE_NAME != value))
				{
					this._MODULE_NAME = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
