#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPR_OCEL_Enhance.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_ONLINE_EXAM_OCEL")]
	public partial class DtClass_AppsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMenu_Aplikasi(Menu_Aplikasi instance);
    partial void UpdateMenu_Aplikasi(Menu_Aplikasi instance);
    partial void DeleteMenu_Aplikasi(Menu_Aplikasi instance);
    partial void InsertMenu_GP(Menu_GP instance);
    partial void UpdateMenu_GP(Menu_GP instance);
    partial void DeleteMenu_GP(Menu_GP instance);
    partial void InsertTBL_USER(TBL_USER instance);
    partial void UpdateTBL_USER(TBL_USER instance);
    partial void DeleteTBL_USER(TBL_USER instance);
    partial void InsertTBL_T_LOG_APP(TBL_T_LOG_APP instance);
    partial void UpdateTBL_T_LOG_APP(TBL_T_LOG_APP instance);
    partial void DeleteTBL_T_LOG_APP(TBL_T_LOG_APP instance);
    partial void InsertTBL_R_JOINED_DIVISION(TBL_R_JOINED_DIVISION instance);
    partial void UpdateTBL_R_JOINED_DIVISION(TBL_R_JOINED_DIVISION instance);
    partial void DeleteTBL_R_JOINED_DIVISION(TBL_R_JOINED_DIVISION instance);
    partial void InsertTBL_Profile(TBL_Profile instance);
    partial void UpdateTBL_Profile(TBL_Profile instance);
    partial void DeleteTBL_Profile(TBL_Profile instance);
    #endregion
		
		public DtClass_AppsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_ONLINE_EXAM_OCELConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DtClass_AppsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DtClass_AppsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DtClass_AppsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DtClass_AppsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Menu_Aplikasi> Menu_Aplikasis
		{
			get
			{
				return this.GetTable<Menu_Aplikasi>();
			}
		}
		
		public System.Data.Linq.Table<Menu_GP> Menu_GPs
		{
			get
			{
				return this.GetTable<Menu_GP>();
			}
		}
		
		public System.Data.Linq.Table<TBL_USER_ALL> TBL_USER_ALLs
		{
			get
			{
				return this.GetTable<TBL_USER_ALL>();
			}
		}
		
		public System.Data.Linq.Table<View_Link> View_Links
		{
			get
			{
				return this.GetTable<View_Link>();
			}
		}
		
		public System.Data.Linq.Table<View_Profile> View_Profiles
		{
			get
			{
				return this.GetTable<View_Profile>();
			}
		}
		
		public System.Data.Linq.Table<View_User_ID> View_User_IDs
		{
			get
			{
				return this.GetTable<View_User_ID>();
			}
		}
		
		public System.Data.Linq.Table<View_District> View_Districts
		{
			get
			{
				return this.GetTable<View_District>();
			}
		}
		
		public System.Data.Linq.Table<View_Distrik_Login> View_Distrik_Logins
		{
			get
			{
				return this.GetTable<View_Distrik_Login>();
			}
		}
		
		public System.Data.Linq.Table<vw_Employee> vw_Employees
		{
			get
			{
				return this.GetTable<vw_Employee>();
			}
		}
		
		public System.Data.Linq.Table<Menu> Menus
		{
			get
			{
				return this.GetTable<Menu>();
			}
		}
		
		public System.Data.Linq.Table<TBL_USER> TBL_USERs
		{
			get
			{
				return this.GetTable<TBL_USER>();
			}
		}
		
		public System.Data.Linq.Table<TBL_T_LOG_APP> TBL_T_LOG_APPs
		{
			get
			{
				return this.GetTable<TBL_T_LOG_APP>();
			}
		}
		
		public System.Data.Linq.Table<TBL_R_JOINED_DIVISION> TBL_R_JOINED_DIVISIONs
		{
			get
			{
				return this.GetTable<TBL_R_JOINED_DIVISION>();
			}
		}
		
		public System.Data.Linq.Table<TBL_Profile> TBL_Profiles
		{
			get
			{
				return this.GetTable<TBL_Profile>();
			}
		}
		
		public System.Data.Linq.Table<View_GP_ID> View_GP_IDs
		{
			get
			{
				return this.GetTable<View_GP_ID>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="app.cufn_get_gp_distrik", IsComposable=true)]
		public IQueryable<cufn_get_gp_distrikResult> cufn_get_gp_distrik([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NRP", DbType="VarChar(20)")] string nRP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GP", DbType="Int")] System.Nullable<int> gP)
		{
			return this.CreateMethodCallQuery<cufn_get_gp_distrikResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nRP, gP);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="app.cufn_get_default_distrik", IsComposable=true)]
		public IQueryable<cufn_get_default_distrikResult> cufn_get_default_distrik([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NRP", DbType="VarChar(15)")] string nRP)
		{
			return this.CreateMethodCallQuery<cufn_get_default_distrikResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nRP);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cufn_get_profile_divselect", IsComposable=true)]
		public IQueryable<cufn_get_profile_divselectResult> cufn_get_profile_divselect([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(11)")] string nrp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(4)")] string prodiv)
		{
			return this.CreateMethodCallQuery<cufn_get_profile_divselectResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nrp, prodiv);
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Menu_Aplikasi")]
	public partial class Menu_Aplikasi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Primer;
		
		private int _Id;
		
		private string _Menu;
		
		private System.Nullable<int> _Menu_link;
		
		private string _Link;
		
		private System.Nullable<int> _Urutan;
		
		private string _Deskripsi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPrimerChanging(long value);
    partial void OnPrimerChanged();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMenuChanging(string value);
    partial void OnMenuChanged();
    partial void OnMenu_linkChanging(System.Nullable<int> value);
    partial void OnMenu_linkChanged();
    partial void OnLinkChanging(string value);
    partial void OnLinkChanged();
    partial void OnUrutanChanging(System.Nullable<int> value);
    partial void OnUrutanChanged();
    partial void OnDeskripsiChanging(string value);
    partial void OnDeskripsiChanged();
    #endregion
		
		public Menu_Aplikasi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primer", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long Primer
		{
			get
			{
				return this._Primer;
			}
			set
			{
				if ((this._Primer != value))
				{
					this.OnPrimerChanging(value);
					this.SendPropertyChanging();
					this._Primer = value;
					this.SendPropertyChanged("Primer");
					this.OnPrimerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Menu", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Menu
		{
			get
			{
				return this._Menu;
			}
			set
			{
				if ((this._Menu != value))
				{
					this.OnMenuChanging(value);
					this.SendPropertyChanging();
					this._Menu = value;
					this.SendPropertyChanged("Menu");
					this.OnMenuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Menu_link", DbType="Int")]
		public System.Nullable<int> Menu_link
		{
			get
			{
				return this._Menu_link;
			}
			set
			{
				if ((this._Menu_link != value))
				{
					this.OnMenu_linkChanging(value);
					this.SendPropertyChanging();
					this._Menu_link = value;
					this.SendPropertyChanged("Menu_link");
					this.OnMenu_linkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="NVarChar(250)")]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this.OnLinkChanging(value);
					this.SendPropertyChanging();
					this._Link = value;
					this.SendPropertyChanged("Link");
					this.OnLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Urutan", DbType="Int")]
		public System.Nullable<int> Urutan
		{
			get
			{
				return this._Urutan;
			}
			set
			{
				if ((this._Urutan != value))
				{
					this.OnUrutanChanging(value);
					this.SendPropertyChanging();
					this._Urutan = value;
					this.SendPropertyChanged("Urutan");
					this.OnUrutanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deskripsi", DbType="VarChar(250)")]
		public string Deskripsi
		{
			get
			{
				return this._Deskripsi;
			}
			set
			{
				if ((this._Deskripsi != value))
				{
					this.OnDeskripsiChanging(value);
					this.SendPropertyChanging();
					this._Deskripsi = value;
					this.SendPropertyChanged("Deskripsi");
					this.OnDeskripsiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Menu_GP")]
	public partial class Menu_GP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Primer;
		
		private int _GP_ID;
		
		private string _Permission;
		
		private System.Nullable<bool> _A;
		
		private System.Nullable<bool> _D;
		
		private System.Nullable<bool> _E;
		
		private System.Nullable<bool> _R;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPrimerChanging(long value);
    partial void OnPrimerChanged();
    partial void OnGP_IDChanging(int value);
    partial void OnGP_IDChanged();
    partial void OnPermissionChanging(string value);
    partial void OnPermissionChanged();
    partial void OnAChanging(System.Nullable<bool> value);
    partial void OnAChanged();
    partial void OnDChanging(System.Nullable<bool> value);
    partial void OnDChanged();
    partial void OnEChanging(System.Nullable<bool> value);
    partial void OnEChanged();
    partial void OnRChanging(System.Nullable<bool> value);
    partial void OnRChanged();
    #endregion
		
		public Menu_GP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primer", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Primer
		{
			get
			{
				return this._Primer;
			}
			set
			{
				if ((this._Primer != value))
				{
					this.OnPrimerChanging(value);
					this.SendPropertyChanging();
					this._Primer = value;
					this.SendPropertyChanged("Primer");
					this.OnPrimerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GP_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int GP_ID
		{
			get
			{
				return this._GP_ID;
			}
			set
			{
				if ((this._GP_ID != value))
				{
					this.OnGP_IDChanging(value);
					this.SendPropertyChanging();
					this._GP_ID = value;
					this.SendPropertyChanged("GP_ID");
					this.OnGP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Permission", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Permission
		{
			get
			{
				return this._Permission;
			}
			set
			{
				if ((this._Permission != value))
				{
					this.OnPermissionChanging(value);
					this.SendPropertyChanging();
					this._Permission = value;
					this.SendPropertyChanged("Permission");
					this.OnPermissionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A", DbType="Bit")]
		public System.Nullable<bool> A
		{
			get
			{
				return this._A;
			}
			set
			{
				if ((this._A != value))
				{
					this.OnAChanging(value);
					this.SendPropertyChanging();
					this._A = value;
					this.SendPropertyChanged("A");
					this.OnAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D", DbType="Bit")]
		public System.Nullable<bool> D
		{
			get
			{
				return this._D;
			}
			set
			{
				if ((this._D != value))
				{
					this.OnDChanging(value);
					this.SendPropertyChanging();
					this._D = value;
					this.SendPropertyChanged("D");
					this.OnDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E", DbType="Bit")]
		public System.Nullable<bool> E
		{
			get
			{
				return this._E;
			}
			set
			{
				if ((this._E != value))
				{
					this.OnEChanging(value);
					this.SendPropertyChanging();
					this._E = value;
					this.SendPropertyChanged("E");
					this.OnEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R", DbType="Bit")]
		public System.Nullable<bool> R
		{
			get
			{
				return this._R;
			}
			set
			{
				if ((this._R != value))
				{
					this.OnRChanging(value);
					this.SendPropertyChanging();
					this._R = value;
					this.SendPropertyChanged("R");
					this.OnRChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_USER_ALL")]
	public partial class TBL_USER_ALL
	{
		
		private int _ID;
		
		private string _NRP;
		
		private int _GP;
		
		private string _DISTRIK;
		
		private System.Nullable<int> _Autorize;
		
		public TBL_USER_ALL()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(50)")]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this._NRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GP", DbType="Int NOT NULL")]
		public int GP
		{
			get
			{
				return this._GP;
			}
			set
			{
				if ((this._GP != value))
				{
					this._GP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTRIK", DbType="VarChar(50)")]
		public string DISTRIK
		{
			get
			{
				return this._DISTRIK;
			}
			set
			{
				if ((this._DISTRIK != value))
				{
					this._DISTRIK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Autorize", DbType="Int")]
		public System.Nullable<int> Autorize
		{
			get
			{
				return this._Autorize;
			}
			set
			{
				if ((this._Autorize != value))
				{
					this._Autorize = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_Link")]
	public partial class View_Link
	{
		
		private int _link;
		
		public View_Link()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="Int NOT NULL")]
		public int link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this._link = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_Profile")]
	public partial class View_Profile
	{
		
		private long _GP_ID;
		
		private string _Deskripsi;
		
		public View_Profile()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GP_ID", DbType="BigInt NOT NULL")]
		public long GP_ID
		{
			get
			{
				return this._GP_ID;
			}
			set
			{
				if ((this._GP_ID != value))
				{
					this._GP_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deskripsi", DbType="VarChar(50)")]
		public string Deskripsi
		{
			get
			{
				return this._Deskripsi;
			}
			set
			{
				if ((this._Deskripsi != value))
				{
					this._Deskripsi = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_User_ID")]
	public partial class View_User_ID
	{
		
		private string _NRP;
		
		private int _GP;
		
		private string _DISTRIK;
		
		private int _ID;
		
		private string _Deskripsi;
		
		private string _KARY_NAMA;
		
		private string _KARY_DIST;
		
		private string _KARY_POS;
		
		public View_User_ID()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this._NRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GP", DbType="Int NOT NULL")]
		public int GP
		{
			get
			{
				return this._GP;
			}
			set
			{
				if ((this._GP != value))
				{
					this._GP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTRIK", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DISTRIK
		{
			get
			{
				return this._DISTRIK;
			}
			set
			{
				if ((this._DISTRIK != value))
				{
					this._DISTRIK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deskripsi", DbType="VarChar(50)")]
		public string Deskripsi
		{
			get
			{
				return this._Deskripsi;
			}
			set
			{
				if ((this._Deskripsi != value))
				{
					this._Deskripsi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KARY_NAMA", DbType="VarChar(43)")]
		public string KARY_NAMA
		{
			get
			{
				return this._KARY_NAMA;
			}
			set
			{
				if ((this._KARY_NAMA != value))
				{
					this._KARY_NAMA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KARY_DIST", DbType="VarChar(4)")]
		public string KARY_DIST
		{
			get
			{
				return this._KARY_DIST;
			}
			set
			{
				if ((this._KARY_DIST != value))
				{
					this._KARY_DIST = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KARY_POS", DbType="VarChar(40)")]
		public string KARY_POS
		{
			get
			{
				return this._KARY_POS;
			}
			set
			{
				if ((this._KARY_POS != value))
				{
					this._KARY_POS = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_District")]
	public partial class View_District
	{
		
		private string _DSTRCT_CODE;
		
		private string _DSTRCT_CODE1;
		
		public View_District()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this._DSTRCT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DSTRCT_CODE1
		{
			get
			{
				return this._DSTRCT_CODE1;
			}
			set
			{
				if ((this._DSTRCT_CODE1 != value))
				{
					this._DSTRCT_CODE1 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_Distrik_Login")]
	public partial class View_Distrik_Login
	{
		
		private string _NRP;
		
		private string _DISTRIK;
		
		private int _GP;
		
		private string _POSITION_ID;
		
		public View_Distrik_Login()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this._NRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTRIK", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DISTRIK
		{
			get
			{
				return this._DISTRIK;
			}
			set
			{
				if ((this._DISTRIK != value))
				{
					this._DISTRIK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GP", DbType="Int NOT NULL")]
		public int GP
		{
			get
			{
				return this._GP;
			}
			set
			{
				if ((this._GP != value))
				{
					this._GP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_ID", DbType="VarChar(10)")]
		public string POSITION_ID
		{
			get
			{
				return this._POSITION_ID;
			}
			set
			{
				if ((this._POSITION_ID != value))
				{
					this._POSITION_ID = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_Employee")]
	public partial class vw_Employee
	{
		
		private string _EMPLOYEE_ID;
		
		private string _DSTRCT_CODE;
		
		private string _DEPT_CODE;
		
		private string _DEPT_CODE_DESC;
		
		private string _DIV_CODE;
		
		private string _DIV_CODE_DESC;
		
		private string _GOLONGAN_ID;
		
		private string _GOL_START_DATE;
		
		private string _NRP;
		
		private string _EMPLOYEE_NAME;
		
		private string _POSITION_ID;
		
		private string _POSITION_DESC;
		
		private string _BIRTH_DATE;
		
		private string _GOLONGAN;
		
		private string _HIRE_DATE;
		
		private string _HIRE_YEAR;
		
		private string _POSITION_START_DATE;
		
		private string _EMP_TYPE;
		
		private string _EMP_STATUS;
		
		private string _KODE_ULAP;
		
		private string _Address_LotusNotes;
		
		private string _STATUS_HIRE;
		
		public vw_Employee()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPLOYEE_ID", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string EMPLOYEE_ID
		{
			get
			{
				return this._EMPLOYEE_ID;
			}
			set
			{
				if ((this._EMPLOYEE_ID != value))
				{
					this._EMPLOYEE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(4)")]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this._DSTRCT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE", DbType="VarChar(4)")]
		public string DEPT_CODE
		{
			get
			{
				return this._DEPT_CODE;
			}
			set
			{
				if ((this._DEPT_CODE != value))
				{
					this._DEPT_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEPT_CODE_DESC", DbType="VarChar(50)")]
		public string DEPT_CODE_DESC
		{
			get
			{
				return this._DEPT_CODE_DESC;
			}
			set
			{
				if ((this._DEPT_CODE_DESC != value))
				{
					this._DEPT_CODE_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIV_CODE", DbType="VarChar(4)")]
		public string DIV_CODE
		{
			get
			{
				return this._DIV_CODE;
			}
			set
			{
				if ((this._DIV_CODE != value))
				{
					this._DIV_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIV_CODE_DESC", DbType="VarChar(50)")]
		public string DIV_CODE_DESC
		{
			get
			{
				return this._DIV_CODE_DESC;
			}
			set
			{
				if ((this._DIV_CODE_DESC != value))
				{
					this._DIV_CODE_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GOLONGAN_ID", DbType="VarChar(2)")]
		public string GOLONGAN_ID
		{
			get
			{
				return this._GOLONGAN_ID;
			}
			set
			{
				if ((this._GOLONGAN_ID != value))
				{
					this._GOLONGAN_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GOL_START_DATE", DbType="VarChar(8)")]
		public string GOL_START_DATE
		{
			get
			{
				return this._GOL_START_DATE;
			}
			set
			{
				if ((this._GOL_START_DATE != value))
				{
					this._GOL_START_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(10)")]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this._NRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPLOYEE_NAME", DbType="VarChar(43)")]
		public string EMPLOYEE_NAME
		{
			get
			{
				return this._EMPLOYEE_NAME;
			}
			set
			{
				if ((this._EMPLOYEE_NAME != value))
				{
					this._EMPLOYEE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_ID", DbType="VarChar(10)")]
		public string POSITION_ID
		{
			get
			{
				return this._POSITION_ID;
			}
			set
			{
				if ((this._POSITION_ID != value))
				{
					this._POSITION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_DESC", DbType="VarChar(40)")]
		public string POSITION_DESC
		{
			get
			{
				return this._POSITION_DESC;
			}
			set
			{
				if ((this._POSITION_DESC != value))
				{
					this._POSITION_DESC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTH_DATE", DbType="VarChar(8)")]
		public string BIRTH_DATE
		{
			get
			{
				return this._BIRTH_DATE;
			}
			set
			{
				if ((this._BIRTH_DATE != value))
				{
					this._BIRTH_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GOLONGAN", DbType="VarChar(2)")]
		public string GOLONGAN
		{
			get
			{
				return this._GOLONGAN;
			}
			set
			{
				if ((this._GOLONGAN != value))
				{
					this._GOLONGAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIRE_DATE", DbType="VarChar(8)")]
		public string HIRE_DATE
		{
			get
			{
				return this._HIRE_DATE;
			}
			set
			{
				if ((this._HIRE_DATE != value))
				{
					this._HIRE_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIRE_YEAR", DbType="VarChar(4)")]
		public string HIRE_YEAR
		{
			get
			{
				return this._HIRE_YEAR;
			}
			set
			{
				if ((this._HIRE_YEAR != value))
				{
					this._HIRE_YEAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION_START_DATE", DbType="VarChar(8)")]
		public string POSITION_START_DATE
		{
			get
			{
				return this._POSITION_START_DATE;
			}
			set
			{
				if ((this._POSITION_START_DATE != value))
				{
					this._POSITION_START_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_TYPE", DbType="VarChar(3)")]
		public string EMP_TYPE
		{
			get
			{
				return this._EMP_TYPE;
			}
			set
			{
				if ((this._EMP_TYPE != value))
				{
					this._EMP_TYPE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_STATUS", DbType="VarChar(1)")]
		public string EMP_STATUS
		{
			get
			{
				return this._EMP_STATUS;
			}
			set
			{
				if ((this._EMP_STATUS != value))
				{
					this._EMP_STATUS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KODE_ULAP", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string KODE_ULAP
		{
			get
			{
				return this._KODE_ULAP;
			}
			set
			{
				if ((this._KODE_ULAP != value))
				{
					this._KODE_ULAP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_LotusNotes", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Address_LotusNotes
		{
			get
			{
				return this._Address_LotusNotes;
			}
			set
			{
				if ((this._Address_LotusNotes != value))
				{
					this._Address_LotusNotes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_HIRE", DbType="VarChar(4)")]
		public string STATUS_HIRE
		{
			get
			{
				return this._STATUS_HIRE;
			}
			set
			{
				if ((this._STATUS_HIRE != value))
				{
					this._STATUS_HIRE = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Menu")]
	public partial class Menu
	{
		
		private int _Id;
		
		private string _Menu1;
		
		private System.Nullable<int> _Menu_link;
		
		private string _Link;
		
		private System.Nullable<int> _Urutan;
		
		private int _GP_ID;
		
		private string _Deskripsi;
		
		private string _Permission;
		
		private System.Nullable<bool> _A;
		
		private System.Nullable<bool> _D;
		
		private System.Nullable<bool> _E;
		
		private System.Nullable<bool> _R;
		
		private string _style_class;
		
		public Menu()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Menu", Storage="_Menu1", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Menu1
		{
			get
			{
				return this._Menu1;
			}
			set
			{
				if ((this._Menu1 != value))
				{
					this._Menu1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Menu_link", DbType="Int")]
		public System.Nullable<int> Menu_link
		{
			get
			{
				return this._Menu_link;
			}
			set
			{
				if ((this._Menu_link != value))
				{
					this._Menu_link = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="NVarChar(250)")]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this._Link = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Urutan", DbType="Int")]
		public System.Nullable<int> Urutan
		{
			get
			{
				return this._Urutan;
			}
			set
			{
				if ((this._Urutan != value))
				{
					this._Urutan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GP_ID", DbType="Int NOT NULL")]
		public int GP_ID
		{
			get
			{
				return this._GP_ID;
			}
			set
			{
				if ((this._GP_ID != value))
				{
					this._GP_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deskripsi", DbType="VarChar(250)")]
		public string Deskripsi
		{
			get
			{
				return this._Deskripsi;
			}
			set
			{
				if ((this._Deskripsi != value))
				{
					this._Deskripsi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Permission", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Permission
		{
			get
			{
				return this._Permission;
			}
			set
			{
				if ((this._Permission != value))
				{
					this._Permission = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A", DbType="Bit")]
		public System.Nullable<bool> A
		{
			get
			{
				return this._A;
			}
			set
			{
				if ((this._A != value))
				{
					this._A = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D", DbType="Bit")]
		public System.Nullable<bool> D
		{
			get
			{
				return this._D;
			}
			set
			{
				if ((this._D != value))
				{
					this._D = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E", DbType="Bit")]
		public System.Nullable<bool> E
		{
			get
			{
				return this._E;
			}
			set
			{
				if ((this._E != value))
				{
					this._E = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R", DbType="Bit")]
		public System.Nullable<bool> R
		{
			get
			{
				return this._R;
			}
			set
			{
				if ((this._R != value))
				{
					this._R = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_style_class", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string style_class
		{
			get
			{
				return this._style_class;
			}
			set
			{
				if ((this._style_class != value))
				{
					this._style_class = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_USER")]
	public partial class TBL_USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _NRP;
		
		private int _GP;
		
		private string _DISTRIK;
		
		private System.Nullable<int> _Autorize;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNRPChanging(string value);
    partial void OnNRPChanged();
    partial void OnGPChanging(int value);
    partial void OnGPChanged();
    partial void OnDISTRIKChanging(string value);
    partial void OnDISTRIKChanged();
    partial void OnAutorizeChanging(System.Nullable<int> value);
    partial void OnAutorizeChanged();
    #endregion
		
		public TBL_USER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this.OnNRPChanging(value);
					this.SendPropertyChanging();
					this._NRP = value;
					this.SendPropertyChanged("NRP");
					this.OnNRPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GP", DbType="Int NOT NULL")]
		public int GP
		{
			get
			{
				return this._GP;
			}
			set
			{
				if ((this._GP != value))
				{
					this.OnGPChanging(value);
					this.SendPropertyChanging();
					this._GP = value;
					this.SendPropertyChanged("GP");
					this.OnGPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTRIK", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DISTRIK
		{
			get
			{
				return this._DISTRIK;
			}
			set
			{
				if ((this._DISTRIK != value))
				{
					this.OnDISTRIKChanging(value);
					this.SendPropertyChanging();
					this._DISTRIK = value;
					this.SendPropertyChanged("DISTRIK");
					this.OnDISTRIKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Autorize", DbType="Int")]
		public System.Nullable<int> Autorize
		{
			get
			{
				return this._Autorize;
			}
			set
			{
				if ((this._Autorize != value))
				{
					this.OnAutorizeChanging(value);
					this.SendPropertyChanging();
					this._Autorize = value;
					this.SendPropertyChanged("Autorize");
					this.OnAutorizeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_LOG_APP")]
	public partial class TBL_T_LOG_APP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_LOGIN;
		
		private string _NRP;
		
		private System.DateTime _LOG_DATE_TIME;
		
		private int _LOG_PROFILE;
		
		private string _REMARK;
		
		private string _LOGIN_BY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_LOGINChanging(string value);
    partial void OnID_LOGINChanged();
    partial void OnNRPChanging(string value);
    partial void OnNRPChanged();
    partial void OnLOG_DATE_TIMEChanging(System.DateTime value);
    partial void OnLOG_DATE_TIMEChanged();
    partial void OnLOG_PROFILEChanging(int value);
    partial void OnLOG_PROFILEChanged();
    partial void OnREMARKChanging(string value);
    partial void OnREMARKChanged();
    partial void OnLOGIN_BYChanging(string value);
    partial void OnLOGIN_BYChanged();
    #endregion
		
		public TBL_T_LOG_APP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOGIN", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_LOGIN
		{
			get
			{
				return this._ID_LOGIN;
			}
			set
			{
				if ((this._ID_LOGIN != value))
				{
					this.OnID_LOGINChanging(value);
					this.SendPropertyChanging();
					this._ID_LOGIN = value;
					this.SendPropertyChanged("ID_LOGIN");
					this.OnID_LOGINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this.OnNRPChanging(value);
					this.SendPropertyChanging();
					this._NRP = value;
					this.SendPropertyChanged("NRP");
					this.OnNRPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOG_DATE_TIME", DbType="DateTime NOT NULL")]
		public System.DateTime LOG_DATE_TIME
		{
			get
			{
				return this._LOG_DATE_TIME;
			}
			set
			{
				if ((this._LOG_DATE_TIME != value))
				{
					this.OnLOG_DATE_TIMEChanging(value);
					this.SendPropertyChanging();
					this._LOG_DATE_TIME = value;
					this.SendPropertyChanged("LOG_DATE_TIME");
					this.OnLOG_DATE_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOG_PROFILE", DbType="Int NOT NULL")]
		public int LOG_PROFILE
		{
			get
			{
				return this._LOG_PROFILE;
			}
			set
			{
				if ((this._LOG_PROFILE != value))
				{
					this.OnLOG_PROFILEChanging(value);
					this.SendPropertyChanging();
					this._LOG_PROFILE = value;
					this.SendPropertyChanged("LOG_PROFILE");
					this.OnLOG_PROFILEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REMARK", DbType="VarChar(100)")]
		public string REMARK
		{
			get
			{
				return this._REMARK;
			}
			set
			{
				if ((this._REMARK != value))
				{
					this.OnREMARKChanging(value);
					this.SendPropertyChanging();
					this._REMARK = value;
					this.SendPropertyChanged("REMARK");
					this.OnREMARKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOGIN_BY", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string LOGIN_BY
		{
			get
			{
				return this._LOGIN_BY;
			}
			set
			{
				if ((this._LOGIN_BY != value))
				{
					this.OnLOGIN_BYChanging(value);
					this.SendPropertyChanging();
					this._LOGIN_BY = value;
					this.SendPropertyChanged("LOGIN_BY");
					this.OnLOGIN_BYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="app.TBL_R_JOINED_DIVISION")]
	public partial class TBL_R_JOINED_DIVISION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PID_DIV;
		
		private string _DIV_CODE;
		
		private string _DIV_NAME;
		
		private bool _IS_ACTIVE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPID_DIVChanging(int value);
    partial void OnPID_DIVChanged();
    partial void OnDIV_CODEChanging(string value);
    partial void OnDIV_CODEChanged();
    partial void OnDIV_NAMEChanging(string value);
    partial void OnDIV_NAMEChanged();
    partial void OnIS_ACTIVEChanging(bool value);
    partial void OnIS_ACTIVEChanged();
    #endregion
		
		public TBL_R_JOINED_DIVISION()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PID_DIV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PID_DIV
		{
			get
			{
				return this._PID_DIV;
			}
			set
			{
				if ((this._PID_DIV != value))
				{
					this.OnPID_DIVChanging(value);
					this.SendPropertyChanging();
					this._PID_DIV = value;
					this.SendPropertyChanged("PID_DIV");
					this.OnPID_DIVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIV_CODE", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string DIV_CODE
		{
			get
			{
				return this._DIV_CODE;
			}
			set
			{
				if ((this._DIV_CODE != value))
				{
					this.OnDIV_CODEChanging(value);
					this.SendPropertyChanging();
					this._DIV_CODE = value;
					this.SendPropertyChanged("DIV_CODE");
					this.OnDIV_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIV_NAME", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string DIV_NAME
		{
			get
			{
				return this._DIV_NAME;
			}
			set
			{
				if ((this._DIV_NAME != value))
				{
					this.OnDIV_NAMEChanging(value);
					this.SendPropertyChanging();
					this._DIV_NAME = value;
					this.SendPropertyChanged("DIV_NAME");
					this.OnDIV_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_ACTIVE", DbType="Bit NOT NULL")]
		public bool IS_ACTIVE
		{
			get
			{
				return this._IS_ACTIVE;
			}
			set
			{
				if ((this._IS_ACTIVE != value))
				{
					this.OnIS_ACTIVEChanging(value);
					this.SendPropertyChanging();
					this._IS_ACTIVE = value;
					this.SendPropertyChanged("IS_ACTIVE");
					this.OnIS_ACTIVEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_Profile")]
	public partial class TBL_Profile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _GP_ID;
		
		private string _Deskripsi;
		
		private bool _Is_active;
		
		private string _Accept_by;
		
		private string _Create_OnDistrict;
		
		private System.DateTime _Create_date;
		
		private string _Update_by;
		
		private System.DateTime _Update_date;
		
		private string _Update_OnDistrict;
		
		private string _DivCode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGP_IDChanging(long value);
    partial void OnGP_IDChanged();
    partial void OnDeskripsiChanging(string value);
    partial void OnDeskripsiChanged();
    partial void OnIs_activeChanging(bool value);
    partial void OnIs_activeChanged();
    partial void OnAccept_byChanging(string value);
    partial void OnAccept_byChanged();
    partial void OnCreate_OnDistrictChanging(string value);
    partial void OnCreate_OnDistrictChanged();
    partial void OnCreate_dateChanging(System.DateTime value);
    partial void OnCreate_dateChanged();
    partial void OnUpdate_byChanging(string value);
    partial void OnUpdate_byChanged();
    partial void OnUpdate_dateChanging(System.DateTime value);
    partial void OnUpdate_dateChanged();
    partial void OnUpdate_OnDistrictChanging(string value);
    partial void OnUpdate_OnDistrictChanged();
    partial void OnDivCodeChanging(string value);
    partial void OnDivCodeChanged();
    #endregion
		
		public TBL_Profile()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GP_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long GP_ID
		{
			get
			{
				return this._GP_ID;
			}
			set
			{
				if ((this._GP_ID != value))
				{
					this.OnGP_IDChanging(value);
					this.SendPropertyChanging();
					this._GP_ID = value;
					this.SendPropertyChanged("GP_ID");
					this.OnGP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deskripsi", DbType="VarChar(50)")]
		public string Deskripsi
		{
			get
			{
				return this._Deskripsi;
			}
			set
			{
				if ((this._Deskripsi != value))
				{
					this.OnDeskripsiChanging(value);
					this.SendPropertyChanging();
					this._Deskripsi = value;
					this.SendPropertyChanged("Deskripsi");
					this.OnDeskripsiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Is_active", DbType="Bit NOT NULL")]
		public bool Is_active
		{
			get
			{
				return this._Is_active;
			}
			set
			{
				if ((this._Is_active != value))
				{
					this.OnIs_activeChanging(value);
					this.SendPropertyChanging();
					this._Is_active = value;
					this.SendPropertyChanged("Is_active");
					this.OnIs_activeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Accept_by", DbType="VarChar(15)")]
		public string Accept_by
		{
			get
			{
				return this._Accept_by;
			}
			set
			{
				if ((this._Accept_by != value))
				{
					this.OnAccept_byChanging(value);
					this.SendPropertyChanging();
					this._Accept_by = value;
					this.SendPropertyChanged("Accept_by");
					this.OnAccept_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Create_OnDistrict", DbType="NChar(4)")]
		public string Create_OnDistrict
		{
			get
			{
				return this._Create_OnDistrict;
			}
			set
			{
				if ((this._Create_OnDistrict != value))
				{
					this.OnCreate_OnDistrictChanging(value);
					this.SendPropertyChanging();
					this._Create_OnDistrict = value;
					this.SendPropertyChanged("Create_OnDistrict");
					this.OnCreate_OnDistrictChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Create_date", DbType="DateTime NOT NULL")]
		public System.DateTime Create_date
		{
			get
			{
				return this._Create_date;
			}
			set
			{
				if ((this._Create_date != value))
				{
					this.OnCreate_dateChanging(value);
					this.SendPropertyChanging();
					this._Create_date = value;
					this.SendPropertyChanged("Create_date");
					this.OnCreate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Update_by", DbType="VarChar(15)")]
		public string Update_by
		{
			get
			{
				return this._Update_by;
			}
			set
			{
				if ((this._Update_by != value))
				{
					this.OnUpdate_byChanging(value);
					this.SendPropertyChanging();
					this._Update_by = value;
					this.SendPropertyChanged("Update_by");
					this.OnUpdate_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Update_date", DbType="DateTime NOT NULL")]
		public System.DateTime Update_date
		{
			get
			{
				return this._Update_date;
			}
			set
			{
				if ((this._Update_date != value))
				{
					this.OnUpdate_dateChanging(value);
					this.SendPropertyChanging();
					this._Update_date = value;
					this.SendPropertyChanged("Update_date");
					this.OnUpdate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Update_OnDistrict", DbType="NChar(4)")]
		public string Update_OnDistrict
		{
			get
			{
				return this._Update_OnDistrict;
			}
			set
			{
				if ((this._Update_OnDistrict != value))
				{
					this.OnUpdate_OnDistrictChanging(value);
					this.SendPropertyChanging();
					this._Update_OnDistrict = value;
					this.SendPropertyChanged("Update_OnDistrict");
					this.OnUpdate_OnDistrictChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DivCode", DbType="VarChar(4)")]
		public string DivCode
		{
			get
			{
				return this._DivCode;
			}
			set
			{
				if ((this._DivCode != value))
				{
					this.OnDivCodeChanging(value);
					this.SendPropertyChanging();
					this._DivCode = value;
					this.SendPropertyChanged("DivCode");
					this.OnDivCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="app.View_GP_ID")]
	public partial class View_GP_ID
	{
		
		private int _GP;
		
		private string _NRP;
		
		private string _Deskripsi;
		
		private string _ProDivisi;
		
		private string _Deskripsi_ID;
		
		private int _ID;
		
		private string _DISTRIK;
		
		private string _DIV_CODE;
		
		private string _NAMA;
		
		private int _IS_MANAGER;
		
		public View_GP_ID()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GP", DbType="Int NOT NULL")]
		public int GP
		{
			get
			{
				return this._GP;
			}
			set
			{
				if ((this._GP != value))
				{
					this._GP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NRP", DbType="VarChar(50)")]
		public string NRP
		{
			get
			{
				return this._NRP;
			}
			set
			{
				if ((this._NRP != value))
				{
					this._NRP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deskripsi", DbType="VarChar(91)")]
		public string Deskripsi
		{
			get
			{
				return this._Deskripsi;
			}
			set
			{
				if ((this._Deskripsi != value))
				{
					this._Deskripsi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProDivisi", DbType="VarChar(4)")]
		public string ProDivisi
		{
			get
			{
				return this._ProDivisi;
			}
			set
			{
				if ((this._ProDivisi != value))
				{
					this._ProDivisi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deskripsi_ID", DbType="VarChar(50)")]
		public string Deskripsi_ID
		{
			get
			{
				return this._Deskripsi_ID;
			}
			set
			{
				if ((this._Deskripsi_ID != value))
				{
					this._Deskripsi_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTRIK", DbType="VarChar(50)")]
		public string DISTRIK
		{
			get
			{
				return this._DISTRIK;
			}
			set
			{
				if ((this._DISTRIK != value))
				{
					this._DISTRIK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIV_CODE", DbType="VarChar(4)")]
		public string DIV_CODE
		{
			get
			{
				return this._DIV_CODE;
			}
			set
			{
				if ((this._DIV_CODE != value))
				{
					this._DIV_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMA", DbType="VarChar(43)")]
		public string NAMA
		{
			get
			{
				return this._NAMA;
			}
			set
			{
				if ((this._NAMA != value))
				{
					this._NAMA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IS_MANAGER", DbType="Int NOT NULL")]
		public int IS_MANAGER
		{
			get
			{
				return this._IS_MANAGER;
			}
			set
			{
				if ((this._IS_MANAGER != value))
				{
					this._IS_MANAGER = value;
				}
			}
		}
	}
	
	public partial class cufn_get_gp_distrikResult
	{
		
		private string _DISTRIK;
		
		public cufn_get_gp_distrikResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISTRIK", DbType="VarChar(50)")]
		public string DISTRIK
		{
			get
			{
				return this._DISTRIK;
			}
			set
			{
				if ((this._DISTRIK != value))
				{
					this._DISTRIK = value;
				}
			}
		}
	}
	
	public partial class cufn_get_default_distrikResult
	{
		
		private string _DSTRCT_CODE;
		
		public cufn_get_default_distrikResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DSTRCT_CODE", DbType="VarChar(4)")]
		public string DSTRCT_CODE
		{
			get
			{
				return this._DSTRCT_CODE;
			}
			set
			{
				if ((this._DSTRCT_CODE != value))
				{
					this._DSTRCT_CODE = value;
				}
			}
		}
	}
	
	public partial class cufn_get_profile_divselectResult
	{
		
		private int _GP;
		
		private string _Deskripsi;
		
		public cufn_get_profile_divselectResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GP", DbType="Int NOT NULL")]
		public int GP
		{
			get
			{
				return this._GP;
			}
			set
			{
				if ((this._GP != value))
				{
					this._GP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deskripsi", DbType="VarChar(91)")]
		public string Deskripsi
		{
			get
			{
				return this._Deskripsi;
			}
			set
			{
				if ((this._Deskripsi != value))
				{
					this._Deskripsi = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
