#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPR_OCEL_Enhance.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_online_exam_ocel")]
	public partial class MobileDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_t_answer(tbl_t_answer instance);
    partial void Updatetbl_t_answer(tbl_t_answer instance);
    partial void Deletetbl_t_answer(tbl_t_answer instance);
    partial void Inserttbl_t_registration(tbl_t_registration instance);
    partial void Updatetbl_t_registration(tbl_t_registration instance);
    partial void Deletetbl_t_registration(tbl_t_registration instance);
    partial void Inserttbl_t_event(tbl_t_event instance);
    partial void Updatetbl_t_event(tbl_t_event instance);
    partial void Deletetbl_t_event(tbl_t_event instance);
    partial void Inserttbl_t_events_time_detail(tbl_t_events_time_detail instance);
    partial void Updatetbl_t_events_time_detail(tbl_t_events_time_detail instance);
    partial void Deletetbl_t_events_time_detail(tbl_t_events_time_detail instance);
    partial void Inserttbl_r_handbook(tbl_r_handbook instance);
    partial void Updatetbl_r_handbook(tbl_r_handbook instance);
    partial void Deletetbl_r_handbook(tbl_r_handbook instance);
    partial void Inserttbl_r_test_center(tbl_r_test_center instance);
    partial void Updatetbl_r_test_center(tbl_r_test_center instance);
    partial void Deletetbl_r_test_center(tbl_r_test_center instance);
    partial void Inserttbl_t_request_acessor(tbl_t_request_acessor instance);
    partial void Updatetbl_t_request_acessor(tbl_t_request_acessor instance);
    partial void Deletetbl_t_request_acessor(tbl_t_request_acessor instance);
    #endregion
		
		public MobileDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["db_online_exam_ocelConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MobileDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MobileDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MobileDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MobileDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_t_answer> tbl_t_answers
		{
			get
			{
				return this.GetTable<tbl_t_answer>();
			}
		}
		
		public System.Data.Linq.Table<tbl_t_registration> tbl_t_registrations
		{
			get
			{
				return this.GetTable<tbl_t_registration>();
			}
		}
		
		public System.Data.Linq.Table<tbl_t_event> tbl_t_events
		{
			get
			{
				return this.GetTable<tbl_t_event>();
			}
		}
		
		public System.Data.Linq.Table<tbl_t_events_time_detail> tbl_t_events_time_details
		{
			get
			{
				return this.GetTable<tbl_t_events_time_detail>();
			}
		}
		
		public System.Data.Linq.Table<tbl_r_handbook> tbl_r_handbooks
		{
			get
			{
				return this.GetTable<tbl_r_handbook>();
			}
		}
		
		public System.Data.Linq.Table<tbl_r_test_center> tbl_r_test_centers
		{
			get
			{
				return this.GetTable<tbl_r_test_center>();
			}
		}
		
		public System.Data.Linq.Table<vw_record_new> vw_record_news
		{
			get
			{
				return this.GetTable<vw_record_new>();
			}
		}
		
		public System.Data.Linq.Table<vw_finished_exam_to_sqco> vw_finished_exam_to_sqcos
		{
			get
			{
				return this.GetTable<vw_finished_exam_to_sqco>();
			}
		}
		
		public System.Data.Linq.Table<tbl_t_request_acessor> tbl_t_request_acessors
		{
			get
			{
				return this.GetTable<tbl_t_request_acessor>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="exam.tbl_t_answer")]
	public partial class tbl_t_answer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int @__no;
		
		private string _qa_id;
		
		private string _registration_id;
		
		private string _nrp;
		
		private string _question_id;
		
		private string _answer_user;
		
		private System.Nullable<bool> _status;
		
		private System.Nullable<double> _score;
		
		private int _jenis_soal;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On_noChanging(int value);
    partial void On_noChanged();
    partial void Onqa_idChanging(string value);
    partial void Onqa_idChanged();
    partial void Onregistration_idChanging(string value);
    partial void Onregistration_idChanged();
    partial void OnnrpChanging(string value);
    partial void OnnrpChanged();
    partial void Onquestion_idChanging(string value);
    partial void Onquestion_idChanged();
    partial void Onanswer_userChanging(string value);
    partial void Onanswer_userChanged();
    partial void OnstatusChanging(System.Nullable<bool> value);
    partial void OnstatusChanged();
    partial void OnscoreChanging(System.Nullable<double> value);
    partial void OnscoreChanged();
    partial void Onjenis_soalChanging(int value);
    partial void Onjenis_soalChanged();
    #endregion
		
		public tbl_t_answer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_no]", Storage="__no", DbType="Int NOT NULL")]
		public int _no
		{
			get
			{
				return this.@__no;
			}
			set
			{
				if ((this.@__no != value))
				{
					this.On_noChanging(value);
					this.SendPropertyChanging();
					this.@__no = value;
					this.SendPropertyChanged("_no");
					this.On_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qa_id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string qa_id
		{
			get
			{
				return this._qa_id;
			}
			set
			{
				if ((this._qa_id != value))
				{
					this.Onqa_idChanging(value);
					this.SendPropertyChanging();
					this._qa_id = value;
					this.SendPropertyChanged("qa_id");
					this.Onqa_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_registration_id", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string registration_id
		{
			get
			{
				return this._registration_id;
			}
			set
			{
				if ((this._registration_id != value))
				{
					this.Onregistration_idChanging(value);
					this.SendPropertyChanging();
					this._registration_id = value;
					this.SendPropertyChanged("registration_id");
					this.Onregistration_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nrp", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string nrp
		{
			get
			{
				return this._nrp;
			}
			set
			{
				if ((this._nrp != value))
				{
					this.OnnrpChanging(value);
					this.SendPropertyChanging();
					this._nrp = value;
					this.SendPropertyChanged("nrp");
					this.OnnrpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_question_id", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string question_id
		{
			get
			{
				return this._question_id;
			}
			set
			{
				if ((this._question_id != value))
				{
					this.Onquestion_idChanging(value);
					this.SendPropertyChanging();
					this._question_id = value;
					this.SendPropertyChanged("question_id");
					this.Onquestion_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_answer_user", DbType="VarChar(MAX)")]
		public string answer_user
		{
			get
			{
				return this._answer_user;
			}
			set
			{
				if ((this._answer_user != value))
				{
					this.Onanswer_userChanging(value);
					this.SendPropertyChanging();
					this._answer_user = value;
					this.SendPropertyChanged("answer_user");
					this.Onanswer_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Bit")]
		public System.Nullable<bool> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_score", DbType="Float")]
		public System.Nullable<double> score
		{
			get
			{
				return this._score;
			}
			set
			{
				if ((this._score != value))
				{
					this.OnscoreChanging(value);
					this.SendPropertyChanging();
					this._score = value;
					this.SendPropertyChanged("score");
					this.OnscoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jenis_soal", DbType="Int NOT NULL")]
		public int jenis_soal
		{
			get
			{
				return this._jenis_soal;
			}
			set
			{
				if ((this._jenis_soal != value))
				{
					this.Onjenis_soalChanging(value);
					this.SendPropertyChanging();
					this._jenis_soal = value;
					this.SendPropertyChanged("jenis_soal");
					this.Onjenis_soalChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="exam.tbl_t_registration")]
	public partial class tbl_t_registration : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _record_id;
		
		private string _registration_id;
		
		private string _student_id;
		
		private string _dstrct_code;
		
		private string _egi;
		
		private string _department;
		
		private System.Nullable<int> _period;
		
		private string _position_code;
		
		private string _position_desc;
		
		private System.Nullable<int> _number_of_question;
		
		private System.Nullable<int> _duration_minute;
		
		private System.Nullable<double> _passing_grade_percent;
		
		private System.Nullable<bool> _randomized_answer;
		
		private System.Nullable<bool> _is_self_assesment;
		
		private System.Nullable<System.DateTime> _registration_date;
		
		private string _exam_actual_date;
		
		private System.Nullable<System.DateTime> _exam_login_time;
		
		private System.Nullable<System.DateTime> _exam_finish_time;
		
		private string _exam_comp_id;
		
		private System.Nullable<byte> _exam_status;
		
		private System.Nullable<double> _exam_score;
		
		private string _event_id;
		
		private string _release_by;
		
		private System.Nullable<System.DateTime> _release_date;
		
		private System.Nullable<bool> _status_ready_exam;
		
		private string _support_link;
		
		private System.Nullable<double> _percent_complete;
		
		private System.Nullable<double> _reminding_time;
		
		private System.Nullable<System.DateTime> _update_reminding_time;
		
		private string _exam_start_date;
		
		private System.Nullable<int> _question_type;
		
		private string _sub_module_id;
		
		private System.Nullable<int> _exam_type;
		
		private string _exam_locations;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onrecord_idChanging(string value);
    partial void Onrecord_idChanged();
    partial void Onregistration_idChanging(string value);
    partial void Onregistration_idChanged();
    partial void Onstudent_idChanging(string value);
    partial void Onstudent_idChanged();
    partial void Ondstrct_codeChanging(string value);
    partial void Ondstrct_codeChanged();
    partial void OnegiChanging(string value);
    partial void OnegiChanged();
    partial void OndepartmentChanging(string value);
    partial void OndepartmentChanged();
    partial void OnperiodChanging(System.Nullable<int> value);
    partial void OnperiodChanged();
    partial void Onposition_codeChanging(string value);
    partial void Onposition_codeChanged();
    partial void Onposition_descChanging(string value);
    partial void Onposition_descChanged();
    partial void Onnumber_of_questionChanging(System.Nullable<int> value);
    partial void Onnumber_of_questionChanged();
    partial void Onduration_minuteChanging(System.Nullable<int> value);
    partial void Onduration_minuteChanged();
    partial void Onpassing_grade_percentChanging(System.Nullable<double> value);
    partial void Onpassing_grade_percentChanged();
    partial void Onrandomized_answerChanging(System.Nullable<bool> value);
    partial void Onrandomized_answerChanged();
    partial void Onis_self_assesmentChanging(System.Nullable<bool> value);
    partial void Onis_self_assesmentChanged();
    partial void Onregistration_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onregistration_dateChanged();
    partial void Onexam_actual_dateChanging(string value);
    partial void Onexam_actual_dateChanged();
    partial void Onexam_login_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onexam_login_timeChanged();
    partial void Onexam_finish_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onexam_finish_timeChanged();
    partial void Onexam_comp_idChanging(string value);
    partial void Onexam_comp_idChanged();
    partial void Onexam_statusChanging(System.Nullable<byte> value);
    partial void Onexam_statusChanged();
    partial void Onexam_scoreChanging(System.Nullable<double> value);
    partial void Onexam_scoreChanged();
    partial void Onevent_idChanging(string value);
    partial void Onevent_idChanged();
    partial void Onrelease_byChanging(string value);
    partial void Onrelease_byChanged();
    partial void Onrelease_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onrelease_dateChanged();
    partial void Onstatus_ready_examChanging(System.Nullable<bool> value);
    partial void Onstatus_ready_examChanged();
    partial void Onsupport_linkChanging(string value);
    partial void Onsupport_linkChanged();
    partial void Onpercent_completeChanging(System.Nullable<double> value);
    partial void Onpercent_completeChanged();
    partial void Onreminding_timeChanging(System.Nullable<double> value);
    partial void Onreminding_timeChanged();
    partial void Onupdate_reminding_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_reminding_timeChanged();
    partial void Onexam_start_dateChanging(string value);
    partial void Onexam_start_dateChanged();
    partial void Onquestion_typeChanging(System.Nullable<int> value);
    partial void Onquestion_typeChanged();
    partial void Onsub_module_idChanging(string value);
    partial void Onsub_module_idChanged();
    partial void Onexam_typeChanging(System.Nullable<int> value);
    partial void Onexam_typeChanged();
    partial void Onexam_locationsChanging(string value);
    partial void Onexam_locationsChanged();
    #endregion
		
		public tbl_t_registration()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_record_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string record_id
		{
			get
			{
				return this._record_id;
			}
			set
			{
				if ((this._record_id != value))
				{
					this.Onrecord_idChanging(value);
					this.SendPropertyChanging();
					this._record_id = value;
					this.SendPropertyChanged("record_id");
					this.Onrecord_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_registration_id", DbType="VarChar(100)")]
		public string registration_id
		{
			get
			{
				return this._registration_id;
			}
			set
			{
				if ((this._registration_id != value))
				{
					this.Onregistration_idChanging(value);
					this.SendPropertyChanging();
					this._registration_id = value;
					this.SendPropertyChanged("registration_id");
					this.Onregistration_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_id", DbType="VarChar(10)")]
		public string student_id
		{
			get
			{
				return this._student_id;
			}
			set
			{
				if ((this._student_id != value))
				{
					this.Onstudent_idChanging(value);
					this.SendPropertyChanging();
					this._student_id = value;
					this.SendPropertyChanged("student_id");
					this.Onstudent_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dstrct_code", DbType="VarChar(4)")]
		public string dstrct_code
		{
			get
			{
				return this._dstrct_code;
			}
			set
			{
				if ((this._dstrct_code != value))
				{
					this.Ondstrct_codeChanging(value);
					this.SendPropertyChanging();
					this._dstrct_code = value;
					this.SendPropertyChanged("dstrct_code");
					this.Ondstrct_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_egi", DbType="VarChar(50)")]
		public string egi
		{
			get
			{
				return this._egi;
			}
			set
			{
				if ((this._egi != value))
				{
					this.OnegiChanging(value);
					this.SendPropertyChanging();
					this._egi = value;
					this.SendPropertyChanged("egi");
					this.OnegiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department", DbType="VarChar(250)")]
		public string department
		{
			get
			{
				return this._department;
			}
			set
			{
				if ((this._department != value))
				{
					this.OndepartmentChanging(value);
					this.SendPropertyChanging();
					this._department = value;
					this.SendPropertyChanged("department");
					this.OndepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_period", DbType="Int")]
		public System.Nullable<int> period
		{
			get
			{
				return this._period;
			}
			set
			{
				if ((this._period != value))
				{
					this.OnperiodChanging(value);
					this.SendPropertyChanging();
					this._period = value;
					this.SendPropertyChanged("period");
					this.OnperiodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position_code", DbType="VarChar(50)")]
		public string position_code
		{
			get
			{
				return this._position_code;
			}
			set
			{
				if ((this._position_code != value))
				{
					this.Onposition_codeChanging(value);
					this.SendPropertyChanging();
					this._position_code = value;
					this.SendPropertyChanged("position_code");
					this.Onposition_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position_desc", DbType="VarChar(50)")]
		public string position_desc
		{
			get
			{
				return this._position_desc;
			}
			set
			{
				if ((this._position_desc != value))
				{
					this.Onposition_descChanging(value);
					this.SendPropertyChanging();
					this._position_desc = value;
					this.SendPropertyChanged("position_desc");
					this.Onposition_descChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number_of_question", DbType="Int")]
		public System.Nullable<int> number_of_question
		{
			get
			{
				return this._number_of_question;
			}
			set
			{
				if ((this._number_of_question != value))
				{
					this.Onnumber_of_questionChanging(value);
					this.SendPropertyChanging();
					this._number_of_question = value;
					this.SendPropertyChanged("number_of_question");
					this.Onnumber_of_questionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duration_minute", DbType="Int")]
		public System.Nullable<int> duration_minute
		{
			get
			{
				return this._duration_minute;
			}
			set
			{
				if ((this._duration_minute != value))
				{
					this.Onduration_minuteChanging(value);
					this.SendPropertyChanging();
					this._duration_minute = value;
					this.SendPropertyChanged("duration_minute");
					this.Onduration_minuteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passing_grade_percent", DbType="Float")]
		public System.Nullable<double> passing_grade_percent
		{
			get
			{
				return this._passing_grade_percent;
			}
			set
			{
				if ((this._passing_grade_percent != value))
				{
					this.Onpassing_grade_percentChanging(value);
					this.SendPropertyChanging();
					this._passing_grade_percent = value;
					this.SendPropertyChanged("passing_grade_percent");
					this.Onpassing_grade_percentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_randomized_answer", DbType="Bit")]
		public System.Nullable<bool> randomized_answer
		{
			get
			{
				return this._randomized_answer;
			}
			set
			{
				if ((this._randomized_answer != value))
				{
					this.Onrandomized_answerChanging(value);
					this.SendPropertyChanging();
					this._randomized_answer = value;
					this.SendPropertyChanged("randomized_answer");
					this.Onrandomized_answerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_self_assesment", DbType="Bit")]
		public System.Nullable<bool> is_self_assesment
		{
			get
			{
				return this._is_self_assesment;
			}
			set
			{
				if ((this._is_self_assesment != value))
				{
					this.Onis_self_assesmentChanging(value);
					this.SendPropertyChanging();
					this._is_self_assesment = value;
					this.SendPropertyChanged("is_self_assesment");
					this.Onis_self_assesmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_registration_date", DbType="Date")]
		public System.Nullable<System.DateTime> registration_date
		{
			get
			{
				return this._registration_date;
			}
			set
			{
				if ((this._registration_date != value))
				{
					this.Onregistration_dateChanging(value);
					this.SendPropertyChanging();
					this._registration_date = value;
					this.SendPropertyChanged("registration_date");
					this.Onregistration_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exam_actual_date", DbType="VarChar(40)")]
		public string exam_actual_date
		{
			get
			{
				return this._exam_actual_date;
			}
			set
			{
				if ((this._exam_actual_date != value))
				{
					this.Onexam_actual_dateChanging(value);
					this.SendPropertyChanging();
					this._exam_actual_date = value;
					this.SendPropertyChanged("exam_actual_date");
					this.Onexam_actual_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exam_login_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> exam_login_time
		{
			get
			{
				return this._exam_login_time;
			}
			set
			{
				if ((this._exam_login_time != value))
				{
					this.Onexam_login_timeChanging(value);
					this.SendPropertyChanging();
					this._exam_login_time = value;
					this.SendPropertyChanged("exam_login_time");
					this.Onexam_login_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exam_finish_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> exam_finish_time
		{
			get
			{
				return this._exam_finish_time;
			}
			set
			{
				if ((this._exam_finish_time != value))
				{
					this.Onexam_finish_timeChanging(value);
					this.SendPropertyChanging();
					this._exam_finish_time = value;
					this.SendPropertyChanged("exam_finish_time");
					this.Onexam_finish_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exam_comp_id", DbType="VarChar(100)")]
		public string exam_comp_id
		{
			get
			{
				return this._exam_comp_id;
			}
			set
			{
				if ((this._exam_comp_id != value))
				{
					this.Onexam_comp_idChanging(value);
					this.SendPropertyChanging();
					this._exam_comp_id = value;
					this.SendPropertyChanged("exam_comp_id");
					this.Onexam_comp_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exam_status", DbType="TinyInt")]
		public System.Nullable<byte> exam_status
		{
			get
			{
				return this._exam_status;
			}
			set
			{
				if ((this._exam_status != value))
				{
					this.Onexam_statusChanging(value);
					this.SendPropertyChanging();
					this._exam_status = value;
					this.SendPropertyChanged("exam_status");
					this.Onexam_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exam_score", DbType="Float")]
		public System.Nullable<double> exam_score
		{
			get
			{
				return this._exam_score;
			}
			set
			{
				if ((this._exam_score != value))
				{
					this.Onexam_scoreChanging(value);
					this.SendPropertyChanging();
					this._exam_score = value;
					this.SendPropertyChanged("exam_score");
					this.Onexam_scoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_event_id", DbType="VarChar(100)")]
		public string event_id
		{
			get
			{
				return this._event_id;
			}
			set
			{
				if ((this._event_id != value))
				{
					this.Onevent_idChanging(value);
					this.SendPropertyChanging();
					this._event_id = value;
					this.SendPropertyChanged("event_id");
					this.Onevent_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_release_by", DbType="VarChar(10)")]
		public string release_by
		{
			get
			{
				return this._release_by;
			}
			set
			{
				if ((this._release_by != value))
				{
					this.Onrelease_byChanging(value);
					this.SendPropertyChanging();
					this._release_by = value;
					this.SendPropertyChanged("release_by");
					this.Onrelease_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_release_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> release_date
		{
			get
			{
				return this._release_date;
			}
			set
			{
				if ((this._release_date != value))
				{
					this.Onrelease_dateChanging(value);
					this.SendPropertyChanging();
					this._release_date = value;
					this.SendPropertyChanged("release_date");
					this.Onrelease_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_ready_exam", DbType="Bit")]
		public System.Nullable<bool> status_ready_exam
		{
			get
			{
				return this._status_ready_exam;
			}
			set
			{
				if ((this._status_ready_exam != value))
				{
					this.Onstatus_ready_examChanging(value);
					this.SendPropertyChanging();
					this._status_ready_exam = value;
					this.SendPropertyChanged("status_ready_exam");
					this.Onstatus_ready_examChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_support_link", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string support_link
		{
			get
			{
				return this._support_link;
			}
			set
			{
				if ((this._support_link != value))
				{
					this.Onsupport_linkChanging(value);
					this.SendPropertyChanging();
					this._support_link = value;
					this.SendPropertyChanged("support_link");
					this.Onsupport_linkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_percent_complete", DbType="Float")]
		public System.Nullable<double> percent_complete
		{
			get
			{
				return this._percent_complete;
			}
			set
			{
				if ((this._percent_complete != value))
				{
					this.Onpercent_completeChanging(value);
					this.SendPropertyChanging();
					this._percent_complete = value;
					this.SendPropertyChanged("percent_complete");
					this.Onpercent_completeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reminding_time", DbType="Float")]
		public System.Nullable<double> reminding_time
		{
			get
			{
				return this._reminding_time;
			}
			set
			{
				if ((this._reminding_time != value))
				{
					this.Onreminding_timeChanging(value);
					this.SendPropertyChanging();
					this._reminding_time = value;
					this.SendPropertyChanged("reminding_time");
					this.Onreminding_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_reminding_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_reminding_time
		{
			get
			{
				return this._update_reminding_time;
			}
			set
			{
				if ((this._update_reminding_time != value))
				{
					this.Onupdate_reminding_timeChanging(value);
					this.SendPropertyChanging();
					this._update_reminding_time = value;
					this.SendPropertyChanged("update_reminding_time");
					this.Onupdate_reminding_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exam_start_date", DbType="VarChar(40)")]
		public string exam_start_date
		{
			get
			{
				return this._exam_start_date;
			}
			set
			{
				if ((this._exam_start_date != value))
				{
					this.Onexam_start_dateChanging(value);
					this.SendPropertyChanging();
					this._exam_start_date = value;
					this.SendPropertyChanged("exam_start_date");
					this.Onexam_start_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_question_type", DbType="Int")]
		public System.Nullable<int> question_type
		{
			get
			{
				return this._question_type;
			}
			set
			{
				if ((this._question_type != value))
				{
					this.Onquestion_typeChanging(value);
					this.SendPropertyChanging();
					this._question_type = value;
					this.SendPropertyChanged("question_type");
					this.Onquestion_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sub_module_id", DbType="VarChar(3)")]
		public string sub_module_id
		{
			get
			{
				return this._sub_module_id;
			}
			set
			{
				if ((this._sub_module_id != value))
				{
					this.Onsub_module_idChanging(value);
					this.SendPropertyChanging();
					this._sub_module_id = value;
					this.SendPropertyChanged("sub_module_id");
					this.Onsub_module_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exam_type", DbType="Int")]
		public System.Nullable<int> exam_type
		{
			get
			{
				return this._exam_type;
			}
			set
			{
				if ((this._exam_type != value))
				{
					this.Onexam_typeChanging(value);
					this.SendPropertyChanging();
					this._exam_type = value;
					this.SendPropertyChanged("exam_type");
					this.Onexam_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exam_locations", DbType="VarChar(30)")]
		public string exam_locations
		{
			get
			{
				return this._exam_locations;
			}
			set
			{
				if ((this._exam_locations != value))
				{
					this.Onexam_locationsChanging(value);
					this.SendPropertyChanging();
					this._exam_locations = value;
					this.SendPropertyChanged("exam_locations");
					this.Onexam_locationsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="exam.tbl_t_events")]
	public partial class tbl_t_event : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _event_id;
		
		private string _test_center_id;
		
		private string _certificator_id;
		
		private string _description;
		
		private string _long_description;
		
		private string _module_id;
		
		private string _module_name;
		
		private System.Nullable<System.DateTime> _exam_start;
		
		private System.Nullable<System.DateTime> _exam_end;
		
		private string _question_type;
		
		private string _create_by;
		
		private System.DateTime _create_date;
		
		private string _update_by;
		
		private System.Nullable<System.DateTime> _update_date;
		
		private int _jenis_ujian_code;
		
		private int _exam_target_min;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onevent_idChanging(string value);
    partial void Onevent_idChanged();
    partial void Ontest_center_idChanging(string value);
    partial void Ontest_center_idChanged();
    partial void Oncertificator_idChanging(string value);
    partial void Oncertificator_idChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void Onlong_descriptionChanging(string value);
    partial void Onlong_descriptionChanged();
    partial void Onmodule_idChanging(string value);
    partial void Onmodule_idChanged();
    partial void Onmodule_nameChanging(string value);
    partial void Onmodule_nameChanged();
    partial void Onexam_startChanging(System.Nullable<System.DateTime> value);
    partial void Onexam_startChanged();
    partial void Onexam_endChanging(System.Nullable<System.DateTime> value);
    partial void Onexam_endChanged();
    partial void Onquestion_typeChanging(string value);
    partial void Onquestion_typeChanged();
    partial void Oncreate_byChanging(string value);
    partial void Oncreate_byChanged();
    partial void Oncreate_dateChanging(System.DateTime value);
    partial void Oncreate_dateChanged();
    partial void Onupdate_byChanging(string value);
    partial void Onupdate_byChanged();
    partial void Onupdate_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_dateChanged();
    partial void Onjenis_ujian_codeChanging(int value);
    partial void Onjenis_ujian_codeChanged();
    partial void Onexam_target_minChanging(int value);
    partial void Onexam_target_minChanged();
    #endregion
		
		public tbl_t_event()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_event_id", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string event_id
		{
			get
			{
				return this._event_id;
			}
			set
			{
				if ((this._event_id != value))
				{
					this.Onevent_idChanging(value);
					this.SendPropertyChanging();
					this._event_id = value;
					this.SendPropertyChanged("event_id");
					this.Onevent_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_test_center_id", DbType="VarChar(100)")]
		public string test_center_id
		{
			get
			{
				return this._test_center_id;
			}
			set
			{
				if ((this._test_center_id != value))
				{
					this.Ontest_center_idChanging(value);
					this.SendPropertyChanging();
					this._test_center_id = value;
					this.SendPropertyChanged("test_center_id");
					this.Ontest_center_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_certificator_id", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string certificator_id
		{
			get
			{
				return this._certificator_id;
			}
			set
			{
				if ((this._certificator_id != value))
				{
					this.Oncertificator_idChanging(value);
					this.SendPropertyChanging();
					this._certificator_id = value;
					this.SendPropertyChanged("certificator_id");
					this.Oncertificator_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(100)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_long_description", DbType="VarChar(MAX)")]
		public string long_description
		{
			get
			{
				return this._long_description;
			}
			set
			{
				if ((this._long_description != value))
				{
					this.Onlong_descriptionChanging(value);
					this.SendPropertyChanging();
					this._long_description = value;
					this.SendPropertyChanged("long_description");
					this.Onlong_descriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_module_id", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string module_id
		{
			get
			{
				return this._module_id;
			}
			set
			{
				if ((this._module_id != value))
				{
					this.Onmodule_idChanging(value);
					this.SendPropertyChanging();
					this._module_id = value;
					this.SendPropertyChanged("module_id");
					this.Onmodule_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_module_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string module_name
		{
			get
			{
				return this._module_name;
			}
			set
			{
				if ((this._module_name != value))
				{
					this.Onmodule_nameChanging(value);
					this.SendPropertyChanging();
					this._module_name = value;
					this.SendPropertyChanged("module_name");
					this.Onmodule_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exam_start", DbType="Date")]
		public System.Nullable<System.DateTime> exam_start
		{
			get
			{
				return this._exam_start;
			}
			set
			{
				if ((this._exam_start != value))
				{
					this.Onexam_startChanging(value);
					this.SendPropertyChanging();
					this._exam_start = value;
					this.SendPropertyChanged("exam_start");
					this.Onexam_startChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exam_end", DbType="Date")]
		public System.Nullable<System.DateTime> exam_end
		{
			get
			{
				return this._exam_end;
			}
			set
			{
				if ((this._exam_end != value))
				{
					this.Onexam_endChanging(value);
					this.SendPropertyChanging();
					this._exam_end = value;
					this.SendPropertyChanged("exam_end");
					this.Onexam_endChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_question_type", DbType="VarChar(20)")]
		public string question_type
		{
			get
			{
				return this._question_type;
			}
			set
			{
				if ((this._question_type != value))
				{
					this.Onquestion_typeChanging(value);
					this.SendPropertyChanging();
					this._question_type = value;
					this.SendPropertyChanged("question_type");
					this.Onquestion_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_by", DbType="VarChar(15)")]
		public string create_by
		{
			get
			{
				return this._create_by;
			}
			set
			{
				if ((this._create_by != value))
				{
					this.Oncreate_byChanging(value);
					this.SendPropertyChanging();
					this._create_by = value;
					this.SendPropertyChanged("create_by");
					this.Oncreate_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this.Oncreate_dateChanging(value);
					this.SendPropertyChanging();
					this._create_date = value;
					this.SendPropertyChanged("create_date");
					this.Oncreate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_by", DbType="VarChar(15)")]
		public string update_by
		{
			get
			{
				return this._update_by;
			}
			set
			{
				if ((this._update_by != value))
				{
					this.Onupdate_byChanging(value);
					this.SendPropertyChanging();
					this._update_by = value;
					this.SendPropertyChanged("update_by");
					this.Onupdate_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_date
		{
			get
			{
				return this._update_date;
			}
			set
			{
				if ((this._update_date != value))
				{
					this.Onupdate_dateChanging(value);
					this.SendPropertyChanging();
					this._update_date = value;
					this.SendPropertyChanged("update_date");
					this.Onupdate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jenis_ujian_code", DbType="Int NOT NULL")]
		public int jenis_ujian_code
		{
			get
			{
				return this._jenis_ujian_code;
			}
			set
			{
				if ((this._jenis_ujian_code != value))
				{
					this.Onjenis_ujian_codeChanging(value);
					this.SendPropertyChanging();
					this._jenis_ujian_code = value;
					this.SendPropertyChanged("jenis_ujian_code");
					this.Onjenis_ujian_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exam_target_min", DbType="Int NOT NULL")]
		public int exam_target_min
		{
			get
			{
				return this._exam_target_min;
			}
			set
			{
				if ((this._exam_target_min != value))
				{
					this.Onexam_target_minChanging(value);
					this.SendPropertyChanging();
					this._exam_target_min = value;
					this.SendPropertyChanged("exam_target_min");
					this.Onexam_target_minChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="exam.tbl_t_events_time_detail")]
	public partial class tbl_t_events_time_detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _code_id;
		
		private string _event_id;
		
		private int _question_type;
		
		private int _time_exam;
		
		private System.Nullable<int> _weight;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncode_idChanging(string value);
    partial void Oncode_idChanged();
    partial void Onevent_idChanging(string value);
    partial void Onevent_idChanged();
    partial void Onquestion_typeChanging(int value);
    partial void Onquestion_typeChanged();
    partial void Ontime_examChanging(int value);
    partial void Ontime_examChanged();
    partial void OnweightChanging(System.Nullable<int> value);
    partial void OnweightChanged();
    #endregion
		
		public tbl_t_events_time_detail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string code_id
		{
			get
			{
				return this._code_id;
			}
			set
			{
				if ((this._code_id != value))
				{
					this.Oncode_idChanging(value);
					this.SendPropertyChanging();
					this._code_id = value;
					this.SendPropertyChanged("code_id");
					this.Oncode_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_event_id", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string event_id
		{
			get
			{
				return this._event_id;
			}
			set
			{
				if ((this._event_id != value))
				{
					this.Onevent_idChanging(value);
					this.SendPropertyChanging();
					this._event_id = value;
					this.SendPropertyChanged("event_id");
					this.Onevent_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_question_type", DbType="Int NOT NULL")]
		public int question_type
		{
			get
			{
				return this._question_type;
			}
			set
			{
				if ((this._question_type != value))
				{
					this.Onquestion_typeChanging(value);
					this.SendPropertyChanging();
					this._question_type = value;
					this.SendPropertyChanged("question_type");
					this.Onquestion_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time_exam", DbType="Int NOT NULL")]
		public int time_exam
		{
			get
			{
				return this._time_exam;
			}
			set
			{
				if ((this._time_exam != value))
				{
					this.Ontime_examChanging(value);
					this.SendPropertyChanging();
					this._time_exam = value;
					this.SendPropertyChanged("time_exam");
					this.Ontime_examChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weight", DbType="Int")]
		public System.Nullable<int> weight
		{
			get
			{
				return this._weight;
			}
			set
			{
				if ((this._weight != value))
				{
					this.OnweightChanging(value);
					this.SendPropertyChanging();
					this._weight = value;
					this.SendPropertyChanged("weight");
					this.OnweightChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="enchocel.tbl_r_handbook")]
	public partial class tbl_r_handbook : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _handbook_pid;
		
		private string _module_id;
		
		private string _file_path;
		
		private string _file_name;
		
		private string _egi;
		
		private bool _isactive;
		
		private System.Nullable<System.DateTime> _created_date;
		
		private string _created_by;
		
		private System.Nullable<System.DateTime> _modif_date;
		
		private string _modif_by;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onhandbook_pidChanging(string value);
    partial void Onhandbook_pidChanged();
    partial void Onmodule_idChanging(string value);
    partial void Onmodule_idChanged();
    partial void Onfile_pathChanging(string value);
    partial void Onfile_pathChanged();
    partial void Onfile_nameChanging(string value);
    partial void Onfile_nameChanged();
    partial void OnegiChanging(string value);
    partial void OnegiChanged();
    partial void OnisactiveChanging(bool value);
    partial void OnisactiveChanged();
    partial void Oncreated_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreated_dateChanged();
    partial void Oncreated_byChanging(string value);
    partial void Oncreated_byChanged();
    partial void Onmodif_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onmodif_dateChanged();
    partial void Onmodif_byChanging(string value);
    partial void Onmodif_byChanged();
    #endregion
		
		public tbl_r_handbook()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_handbook_pid", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string handbook_pid
		{
			get
			{
				return this._handbook_pid;
			}
			set
			{
				if ((this._handbook_pid != value))
				{
					this.Onhandbook_pidChanging(value);
					this.SendPropertyChanging();
					this._handbook_pid = value;
					this.SendPropertyChanged("handbook_pid");
					this.Onhandbook_pidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_module_id", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string module_id
		{
			get
			{
				return this._module_id;
			}
			set
			{
				if ((this._module_id != value))
				{
					this.Onmodule_idChanging(value);
					this.SendPropertyChanging();
					this._module_id = value;
					this.SendPropertyChanged("module_id");
					this.Onmodule_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_path", DbType="VarChar(200)")]
		public string file_path
		{
			get
			{
				return this._file_path;
			}
			set
			{
				if ((this._file_path != value))
				{
					this.Onfile_pathChanging(value);
					this.SendPropertyChanging();
					this._file_path = value;
					this.SendPropertyChanged("file_path");
					this.Onfile_pathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string file_name
		{
			get
			{
				return this._file_name;
			}
			set
			{
				if ((this._file_name != value))
				{
					this.Onfile_nameChanging(value);
					this.SendPropertyChanging();
					this._file_name = value;
					this.SendPropertyChanged("file_name");
					this.Onfile_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_egi", DbType="VarChar(50)")]
		public string egi
		{
			get
			{
				return this._egi;
			}
			set
			{
				if ((this._egi != value))
				{
					this.OnegiChanging(value);
					this.SendPropertyChanging();
					this._egi = value;
					this.SendPropertyChanged("egi");
					this.OnegiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isactive", DbType="Bit NOT NULL")]
		public bool isactive
		{
			get
			{
				return this._isactive;
			}
			set
			{
				if ((this._isactive != value))
				{
					this.OnisactiveChanging(value);
					this.SendPropertyChanging();
					this._isactive = value;
					this.SendPropertyChanged("isactive");
					this.OnisactiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> created_date
		{
			get
			{
				return this._created_date;
			}
			set
			{
				if ((this._created_date != value))
				{
					this.Oncreated_dateChanging(value);
					this.SendPropertyChanging();
					this._created_date = value;
					this.SendPropertyChanged("created_date");
					this.Oncreated_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="VarChar(50)")]
		public string created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this.Oncreated_byChanging(value);
					this.SendPropertyChanging();
					this._created_by = value;
					this.SendPropertyChanged("created_by");
					this.Oncreated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modif_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> modif_date
		{
			get
			{
				return this._modif_date;
			}
			set
			{
				if ((this._modif_date != value))
				{
					this.Onmodif_dateChanging(value);
					this.SendPropertyChanging();
					this._modif_date = value;
					this.SendPropertyChanged("modif_date");
					this.Onmodif_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modif_by", DbType="VarChar(10)")]
		public string modif_by
		{
			get
			{
				return this._modif_by;
			}
			set
			{
				if ((this._modif_by != value))
				{
					this.Onmodif_byChanging(value);
					this.SendPropertyChanging();
					this._modif_by = value;
					this.SendPropertyChanged("modif_by");
					this.Onmodif_byChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="exam.tbl_r_test_center")]
	public partial class tbl_r_test_center : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _test_center_id;
		
		private string _test_center_name;
		
		private string _location;
		
		private string _facility_desc;
		
		private System.Nullable<int> _capacity;
		
		private System.Nullable<bool> _check_capacity;
		
		private string _app_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontest_center_idChanging(string value);
    partial void Ontest_center_idChanged();
    partial void Ontest_center_nameChanging(string value);
    partial void Ontest_center_nameChanged();
    partial void OnlocationChanging(string value);
    partial void OnlocationChanged();
    partial void Onfacility_descChanging(string value);
    partial void Onfacility_descChanged();
    partial void OncapacityChanging(System.Nullable<int> value);
    partial void OncapacityChanged();
    partial void Oncheck_capacityChanging(System.Nullable<bool> value);
    partial void Oncheck_capacityChanged();
    partial void Onapp_idChanging(string value);
    partial void Onapp_idChanged();
    #endregion
		
		public tbl_r_test_center()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_test_center_id", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string test_center_id
		{
			get
			{
				return this._test_center_id;
			}
			set
			{
				if ((this._test_center_id != value))
				{
					this.Ontest_center_idChanging(value);
					this.SendPropertyChanging();
					this._test_center_id = value;
					this.SendPropertyChanged("test_center_id");
					this.Ontest_center_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_test_center_name", DbType="VarChar(250)")]
		public string test_center_name
		{
			get
			{
				return this._test_center_name;
			}
			set
			{
				if ((this._test_center_name != value))
				{
					this.Ontest_center_nameChanging(value);
					this.SendPropertyChanging();
					this._test_center_name = value;
					this.SendPropertyChanged("test_center_name");
					this.Ontest_center_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="VarChar(250)")]
		public string location
		{
			get
			{
				return this._location;
			}
			set
			{
				if ((this._location != value))
				{
					this.OnlocationChanging(value);
					this.SendPropertyChanging();
					this._location = value;
					this.SendPropertyChanged("location");
					this.OnlocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_facility_desc", DbType="VarChar(250)")]
		public string facility_desc
		{
			get
			{
				return this._facility_desc;
			}
			set
			{
				if ((this._facility_desc != value))
				{
					this.Onfacility_descChanging(value);
					this.SendPropertyChanging();
					this._facility_desc = value;
					this.SendPropertyChanged("facility_desc");
					this.Onfacility_descChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_capacity", DbType="Int")]
		public System.Nullable<int> capacity
		{
			get
			{
				return this._capacity;
			}
			set
			{
				if ((this._capacity != value))
				{
					this.OncapacityChanging(value);
					this.SendPropertyChanging();
					this._capacity = value;
					this.SendPropertyChanged("capacity");
					this.OncapacityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_check_capacity", DbType="Bit")]
		public System.Nullable<bool> check_capacity
		{
			get
			{
				return this._check_capacity;
			}
			set
			{
				if ((this._check_capacity != value))
				{
					this.Oncheck_capacityChanging(value);
					this.SendPropertyChanging();
					this._check_capacity = value;
					this.SendPropertyChanged("check_capacity");
					this.Oncheck_capacityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_app_id", DbType="VarChar(100)")]
		public string app_id
		{
			get
			{
				return this._app_id;
			}
			set
			{
				if ((this._app_id != value))
				{
					this.Onapp_idChanging(value);
					this.SendPropertyChanging();
					this._app_id = value;
					this.SendPropertyChanged("app_id");
					this.Onapp_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="enchocel.vw_record_new")]
	public partial class vw_record_new
	{
		
		private string _record_id;
		
		public vw_record_new()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_record_id", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string record_id
		{
			get
			{
				return this._record_id;
			}
			set
			{
				if ((this._record_id != value))
				{
					this._record_id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="enchocel.vw_finished_exam_to_sqco")]
	public partial class vw_finished_exam_to_sqco
	{
		
		private string _record_id;
		
		private string _registration_id;
		
		private string _student_id;
		
		private string _dstrct_code;
		
		private string _egi;
		
		private string _position_desc;
		
		private System.Nullable<int> _number_of_question;
		
		private System.Nullable<int> _duration_minute;
		
		private System.Nullable<double> _passing_grade_percent;
		
		private System.Nullable<System.DateTime> _registration_date;
		
		private System.Nullable<System.DateTime> _exam_finish_time;
		
		private System.Nullable<double> _exam_score;
		
		private string _sesi_ujian;
		
		private System.Nullable<int> _question_type;
		
		private string _sub_module_id;
		
		private string _jenis_ujian;
		
		private string _exam_locations;
		
		private string _module_name;
		
		public vw_finished_exam_to_sqco()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_record_id", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string record_id
		{
			get
			{
				return this._record_id;
			}
			set
			{
				if ((this._record_id != value))
				{
					this._record_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_registration_id", DbType="VarChar(100)")]
		public string registration_id
		{
			get
			{
				return this._registration_id;
			}
			set
			{
				if ((this._registration_id != value))
				{
					this._registration_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_id", DbType="VarChar(10)")]
		public string student_id
		{
			get
			{
				return this._student_id;
			}
			set
			{
				if ((this._student_id != value))
				{
					this._student_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dstrct_code", DbType="VarChar(4)")]
		public string dstrct_code
		{
			get
			{
				return this._dstrct_code;
			}
			set
			{
				if ((this._dstrct_code != value))
				{
					this._dstrct_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_egi", DbType="VarChar(50)")]
		public string egi
		{
			get
			{
				return this._egi;
			}
			set
			{
				if ((this._egi != value))
				{
					this._egi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position_desc", DbType="VarChar(50)")]
		public string position_desc
		{
			get
			{
				return this._position_desc;
			}
			set
			{
				if ((this._position_desc != value))
				{
					this._position_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number_of_question", DbType="Int")]
		public System.Nullable<int> number_of_question
		{
			get
			{
				return this._number_of_question;
			}
			set
			{
				if ((this._number_of_question != value))
				{
					this._number_of_question = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duration_minute", DbType="Int")]
		public System.Nullable<int> duration_minute
		{
			get
			{
				return this._duration_minute;
			}
			set
			{
				if ((this._duration_minute != value))
				{
					this._duration_minute = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passing_grade_percent", DbType="Float")]
		public System.Nullable<double> passing_grade_percent
		{
			get
			{
				return this._passing_grade_percent;
			}
			set
			{
				if ((this._passing_grade_percent != value))
				{
					this._passing_grade_percent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_registration_date", DbType="Date")]
		public System.Nullable<System.DateTime> registration_date
		{
			get
			{
				return this._registration_date;
			}
			set
			{
				if ((this._registration_date != value))
				{
					this._registration_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exam_finish_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> exam_finish_time
		{
			get
			{
				return this._exam_finish_time;
			}
			set
			{
				if ((this._exam_finish_time != value))
				{
					this._exam_finish_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exam_score", DbType="Float")]
		public System.Nullable<double> exam_score
		{
			get
			{
				return this._exam_score;
			}
			set
			{
				if ((this._exam_score != value))
				{
					this._exam_score = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sesi_ujian", DbType="VarChar(100)")]
		public string sesi_ujian
		{
			get
			{
				return this._sesi_ujian;
			}
			set
			{
				if ((this._sesi_ujian != value))
				{
					this._sesi_ujian = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_question_type", DbType="Int")]
		public System.Nullable<int> question_type
		{
			get
			{
				return this._question_type;
			}
			set
			{
				if ((this._question_type != value))
				{
					this._question_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sub_module_id", DbType="VarChar(3)")]
		public string sub_module_id
		{
			get
			{
				return this._sub_module_id;
			}
			set
			{
				if ((this._sub_module_id != value))
				{
					this._sub_module_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jenis_ujian", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string jenis_ujian
		{
			get
			{
				return this._jenis_ujian;
			}
			set
			{
				if ((this._jenis_ujian != value))
				{
					this._jenis_ujian = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exam_locations", DbType="VarChar(30)")]
		public string exam_locations
		{
			get
			{
				return this._exam_locations;
			}
			set
			{
				if ((this._exam_locations != value))
				{
					this._exam_locations = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_module_name", DbType="VarChar(250)")]
		public string module_name
		{
			get
			{
				return this._module_name;
			}
			set
			{
				if ((this._module_name != value))
				{
					this._module_name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="enchocel.tbl_t_request_acessor")]
	public partial class tbl_t_request_acessor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _request_pid;
		
		private string _record_id;
		
		private string _certificator_nrp;
		
		private int _jenis_ujian_code;
		
		private System.DateTime _request_date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onrequest_pidChanging(string value);
    partial void Onrequest_pidChanged();
    partial void Onrecord_idChanging(string value);
    partial void Onrecord_idChanged();
    partial void Oncertificator_nrpChanging(string value);
    partial void Oncertificator_nrpChanged();
    partial void Onjenis_ujian_codeChanging(int value);
    partial void Onjenis_ujian_codeChanged();
    partial void Onrequest_dateChanging(System.DateTime value);
    partial void Onrequest_dateChanged();
    #endregion
		
		public tbl_t_request_acessor()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_request_pid", DbType="VarChar(40) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string request_pid
		{
			get
			{
				return this._request_pid;
			}
			set
			{
				if ((this._request_pid != value))
				{
					this.Onrequest_pidChanging(value);
					this.SendPropertyChanging();
					this._request_pid = value;
					this.SendPropertyChanged("request_pid");
					this.Onrequest_pidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_record_id", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string record_id
		{
			get
			{
				return this._record_id;
			}
			set
			{
				if ((this._record_id != value))
				{
					this.Onrecord_idChanging(value);
					this.SendPropertyChanging();
					this._record_id = value;
					this.SendPropertyChanged("record_id");
					this.Onrecord_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_certificator_nrp", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string certificator_nrp
		{
			get
			{
				return this._certificator_nrp;
			}
			set
			{
				if ((this._certificator_nrp != value))
				{
					this.Oncertificator_nrpChanging(value);
					this.SendPropertyChanging();
					this._certificator_nrp = value;
					this.SendPropertyChanged("certificator_nrp");
					this.Oncertificator_nrpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jenis_ujian_code", DbType="Int NOT NULL")]
		public int jenis_ujian_code
		{
			get
			{
				return this._jenis_ujian_code;
			}
			set
			{
				if ((this._jenis_ujian_code != value))
				{
					this.Onjenis_ujian_codeChanging(value);
					this.SendPropertyChanging();
					this._jenis_ujian_code = value;
					this.SendPropertyChanged("jenis_ujian_code");
					this.Onjenis_ujian_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_request_date", DbType="DateTime NOT NULL")]
		public System.DateTime request_date
		{
			get
			{
				return this._request_date;
			}
			set
			{
				if ((this._request_date != value))
				{
					this.Onrequest_dateChanging(value);
					this.SendPropertyChanging();
					this._request_date = value;
					this.SendPropertyChanged("request_date");
					this.Onrequest_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
